### ISSUE TITLE
Helmfile resolves relative paths incorrectly if PWD is a softlink

### ISSUE THREAD

**Issue by reegnz** [helmfile/helmfile#1013]
### Operating system

MacOS Ventura 13.5.2

### Helmfile Version

0.157.0

### Helm Version

3.12.3

### Bug description

When using relative paths (eg. `path: ../../helmfile.yaml`) in `helmfile.yaml`, the relative path should always be resolved to the absolute path, with symlinks being resolved. Otherwise the behaviour of helmfile breaks:
* helmfile behaves differently if the directory it is softlinked and invoked when cd-ing into the softlink.

When you ignore softlinks (eg. resolve them always), the problem just goes away and has a reasonable default behaviour: always picking up relative paths from the real paths, not softlinked ones.

### Example helmfile.yaml

See example repo.

### Error message you've seen (if any)

```
❯ helmfile template
in ./helmfile.yaml: in .helmfiles[0]: in ../../helmfile.yaml: open helmfile.yaml: no such file or directory
```

### Steps to reproduce

https://github.com/reegnz/helmfile-bug

### Working Helmfile Version

never worked correctly

**Comment by reegnz** [comment]
I'm preparing a PR to fix this.

**Comment by reegnz** [comment]
BTW tools like direnv deal with this problem really gracefully already.

**Comment by yxxhero** [comment]
@reegnz good catch.
