### ISSUE TITLE
--wait not passed to helm delete

### ISSUE THREAD

**Issue by anuragagarwal561994** [helmfile/helmfile#1057]
### Operating system

Mac OS

### Helmfile Version

v0.157.0

### Helm Version

v3.13.0

### Bug description

`--wait` is not passed to helm this is needed for proper resource cleanup when there is dependency between charts.

Before this feature, one needs to also think if `--wait` is passed for install or uninstall. I think user should be given an option to control.

### Example helmfile.yaml

NA

### Error message you've seen (if any)

NA

### Steps to reproduce

NA

### Working Helmfile Version

v0.157.0

**Comment by yxxhero** [comment]
@anuragagarwal561994 PR is welcome.

**Comment by felipecrs** [comment]
I even have:

```yaml
helmDefaults:
  wait: true
```

And still `--wait` is not passed to `helm delete`. The workaround is to `helmfile destroy --args=--wait`.

**Comment by felipecrs** [comment]
I do not recommend `--wait` to be always set or set automatically on chart dependency though, the same way it is NOT set automatically for sync operations unless you specify `wait: true`.

**Comment by felipecrs** [comment]
Work is being done at #1080.

**Comment by mabrarov** [comment]
Hi @yxxhero,

What about `.helmDefaults.cascade` option in Helmfile state file? Is it still not passed to `helm delete` command? My team found that without `--cascade foreground` option `helm delete` (`helmfile destroy`) doesn't delete Helm releases correctly, i.e. it can delete NFS CSI driver for Kubernetes before PersistentVolume allocated through that CSI driver is deleted which leads to an orphan folder (matching PeristentVolume) in the NFS share used by NFS CSI driver for Kubernetes.

Thank you.

**Comment by felipecrs** [comment]
I'm using helmDefaults.cascade as foreground since it was introduced, but I never checked if it was being honored or not.

If it indeed is not, I recommend you open a separate bug report.

**Comment by yxxhero** [comment]
Yeah. Please post a new issue. @mabrarov
