### ISSUE TITLE
Chartify does not run in `0.158.0` if path contains `../`

### ISSUE THREAD

**Issue by s4nji** [helmfile/helmfile#1103]
### Operating system

Ubuntu 22.04

### Helmfile Version

0.158.0

### Helm Version

3.13.1

### Bug description

Helmfile `0.158.0` now fails when using a local incomplete chart if the directory contains `../` in its path.

Comparing the logs between `0.157.0` and `0.158.0`, looks like `chartify` somehow doesn't run when the directory contains `../`.

### Example helmfile.yaml

```yaml
releases:
  - name: my-manifests
    namespace: 2023-10-27-helmfile-test
    chart: ../my-manifests
```

### Error message you've seen (if any)

```
Building dependency release=my-manifests, chart=../my-manifests
in ./helmfile.yaml: [building dependencies of local chart: command "/home/runner/bin/helm" exited with non-zero status:

PATH:
  /home/runner/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: build (5 bytes)
  3: ../my-manifests (15 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Chart.yaml file is missing

COMBINED OUTPUT:
  Error: Chart.yaml file is missing]
```

### Steps to reproduce
* Run `helmfile diff` with a release pointing to a directory containing kubernetes manifests (not a complete chart) with `../` in its path.

I have prepared a repository to showcase the issue:  
https://github.com/s4nji/2023-10-27-helmfile/

You can find the differing results between `0.157.0` and `0.158.0` here:  
https://github.com/s4nji/2023-10-27-helmfile/actions/runs/6666598494

### Working Helmfile Version

0.157.0

**Comment by yxxhero** [comment]
@s4nji thanks for your issue. I will work on this.

**Comment by s4nji** [comment]
Can confirm [this is fixed](https://github.com/s4nji/2023-10-27-helmfile/actions/runs/6717757509), thank you!
