### ISSUE TITLE
in ./helmfile.yaml: unable to update deps: no resolved dependency found for "tetragon", running "helmfile deps" may resolve the issue

### ISSUE THREAD

**Issue by jouve** [helmfile/helmfile#1119]
### Operating system

ubuntu

### Helmfile Version

the exact commit is 212c39cb533876eb87b083c2c6cc909ad7b8664c

### Helm Version

-

### Bug description

when I run helmfile deps and there are releases with installed: false, it fails with :

``` 
in ./helmfile.yaml: unable to update deps: no resolved dependency found for "tetragon", running "helmfile deps" may resolve the issue
```

using git bisect, I found the issue is introduced by https://github.com/helmfile/helmfile/pull/1054 

### Example helmfile.yaml

```
releases:
  - chart: cilium/tetragon
    name: tetragon
    namespace: kube-system
    installed: false
    values:
      - tetragon.yaml
```

### Error message you've seen (if any)

in ./helmfile.yaml: unable to update deps: no resolved dependency found for "tetragon", running "helmfile deps" may resolve the issue

### Steps to reproduce

-

### Working Helmfile Version

latest commit working : d5a6553664b7797f54d985fd91d9e5290a7d45a6

**Comment by yxxhero** [comment]
@jouve what's your helmfile version? I can't reproduce your issue.

**Comment by minedetector** [comment]
I am having the same issue, it started from 0.158.0, persists in 0.158.1 as well

**Comment by yxxhero** [comment]
@minedetector could you show the debug logs？ thanks so much.

**Comment by minedetector** [comment]
Could you be a bit more specific, if I just run `helmfile deps` on debug mode I fear it generates too much stuff that I am not allowed to share.

**Comment by yxxhero** [comment]
@minedetector minimal demo is also ok.

**Comment by minedetector** [comment]
is this useful
```
Updating dependency /var/folders/s2/2rcp43qj01nchp4vn77d5p400000gn/T/2525724789
exec: helm --kube-context beta dependency update /var/folders/s2/2rcp43qj01nchp4vn77d5p400000gn/T/2525724789
Hang tight while we grab the latest from your chart repositories...

...Successfully got an update from the "verdaccio" chart repository

...Successfully got an update from the "nvdp" chart repository

...Successfully got an update from the "twuni" chart repository

...Successfully got an update from the "gatekeeper" chart repository

...Successfully got an update from the "cluster-proportional-autoscaler" chart repository

...Successfully got an update from the "opensearch-operator" chart repository

...Successfully got an update from the "mockserver" chart repository

...Successfully got an update from the "dcgm-exporter" chart repository

...Successfully got an update from the "jetstack" chart repository

...Successfully got an update from the "ingress-nginx" chart repository

...Successfully got an update from the "fluent" chart repository

...Successfully got an update from the "opentelemetry" chart repository

...Successfully got an update from the "jenkinsci" chart repository

...Successfully got an update from the "open-telemetry" chart repository

...Successfully got an update from the "eks" chart repository

...Successfully got an update from the "deliveryhero" chart repository

...Successfully got an update from the "istio" chart repository

...Successfully got an update from the "external-secrets" chart repository

...Successfully got an update from the "datadog" chart repository

...Successfully got an update from the "stakater" chart repository

...Successfully got an update from the "sysdig" chart repository

...Successfully got an update from the "renovate" chart repository

...Successfully got an update from the "prometheus-community" chart repository

...Successfully got an update from the "apisix" chart repository

...Successfully got an update from the "grafana-community" chart repository

...Successfully got an update from the "stable" chart repository

...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

Saving 16 charts
Downloading node-problem-detector from repo https://charts.deliveryhero.io/

Downloading gatekeeper from repo https://open-policy-agent.github.io/gatekeeper/charts

Downloading nvidia-device-plugin from repo https://nvidia.github.io/k8s-device-plugin

Downloading dynamodb-chart from repo oci://public.ecr.aws/aws-controllers-k8s

Pulled: public.ecr.aws/aws-controllers-k8s/dynamodb-chart:1.2.3
Digest: sha256:57928db411cd26707f123a30956489df915342653148bc

Downloading ingress-nginx from repo https://kubernetes.github.io/ingress-nginx

Downloading cert-manager from repo https://charts.jetstack.io

Downloading sysdig-deploy from repo https://charts.sysdig.com

Downloading cluster-proportional-autoscaler from repo https://kubernetes-sigs.github.io/cluster-proportional-autoscaler

Downloading base from repo https://istio-release.storage.googleapis.com/charts

Downloading dcgm-exporter from repo https://nvidia.github.io/dcgm-exporter/helm-charts

Downloading fluent-bit from repo https://fluent.github.io/helm-charts

Downloading reloader from repo https://stakater.github.io/stakater-charts

Downloading aws-load-balancer-controller from repo https://aws.github.io/eks-charts

Downloading opentelemetry-operator from repo https://open-telemetry.github.io/opentelemetry-helm-charts

Downloading external-secrets from repo https://charts.external-secrets.io

Downloading istiod from repo https://istio-release.storage.googleapis.com/charts

Deleting outdated charts

Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "verdaccio" chart repository
...Successfully got an update from the "nvdp" chart repository
...Successfully got an update from the "twuni" chart repository
...Successfully got an update from the "gatekeeper" chart repository
...Successfully got an update from the "cluster-proportional-autoscaler" chart repository
...Successfully got an update from the "opensearch-operator" chart repository
...Successfully got an update from the "mockserver" chart repository
...Successfully got an update from the "dcgm-exporter" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "fluent" chart repository
...Successfully got an update from the "opentelemetry" chart repository
...Successfully got an update from the "jenkinsci" chart repository
...Successfully got an update from the "open-telemetry" chart repository
...Successfully got an update from the "eks" chart repository
...Successfully got an update from the "deliveryhero" chart repository
...Successfully got an update from the "istio" chart repository
...Successfully got an update from the "external-secrets" chart repository
...Successfully got an update from the "datadog" chart repository
...Successfully got an update from the "stakater" chart repository
...Successfully got an update from the "sysdig" chart repository
...Successfully got an update from the "renovate" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "apisix" chart repository
...Successfully got an update from the "grafana-community" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 16 charts
Downloading node-problem-detector from repo https://charts.deliveryhero.io/
Downloading gatekeeper from repo https://open-policy-agent.github.io/gatekeeper/charts
Downloading nvidia-device-plugin from repo https://nvidia.github.io/k8s-device-plugin
Downloading dynamodb-chart from repo oci://public.ecr.aws/aws-controllers-k8s
Downloading ingress-nginx from repo https://kubernetes.github.io/ingress-nginx
Downloading cert-manager from repo https://charts.jetstack.io
Downloading sysdig-deploy from repo https://charts.sysdig.com
Downloading cluster-proportional-autoscaler from repo https://kubernetes-sigs.github.io/cluster-proportional-autoscaler
Downloading base from repo https://istio-release.storage.googleapis.com/charts
Downloading dcgm-exporter from repo https://nvidia.github.io/dcgm-exporter/helm-charts
Downloading fluent-bit from repo https://fluent.github.io/helm-charts
Downloading reloader from repo https://stakater.github.io/stakater-charts
Downloading aws-load-balancer-controller from repo https://aws.github.io/eks-charts
Downloading opentelemetry-operator from repo https://open-telemetry.github.io/opentelemetry-helm-charts
Downloading external-secrets from repo https://charts.external-secrets.io
Downloading istiod from repo https://istio-release.storage.googleapis.com/charts
Deleting outdated charts

readBytes: read from helmfile.env.lock:
version: 0.158.1
dependencies:
- name: aws-load-balancer-controller
  repository: https://aws.github.io/eks-charts
  version: 1.6.1
- name: base
  repository: https://istio-release.storage.googleapis.com/charts
  version: 1.16.4
- name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.13.1
- name: cluster-proportional-autoscaler
  repository: https://kubernetes-sigs.github.io/cluster-proportional-autoscaler
  version: 1.1.0
- name: dcgm-exporter
  repository: https://nvidia.github.io/dcgm-exporter/helm-charts
  version: 3.1.7
- name: dynamodb-chart
  repository: oci://public.ecr.aws/aws-controllers-k8s
  version: 1.2.3
- name: external-secrets
  repository: https://charts.external-secrets.io
  version: 0.9.7
- name: fluent-bit
  repository: https://fluent.github.io/helm-charts
  version: 0.39.0
- name: gatekeeper
  repository: https://open-policy-agent.github.io/gatekeeper/charts
  version: 3.13.3
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.8.0
- name: istiod
  repository: https://istio-release.storage.googleapis.com/charts
  version: 1.16.4
- name: node-problem-detector
  repository: https://charts.deliveryhero.io/
  version: 2.3.11
- name: nvidia-device-plugin
  repository: https://nvidia.github.io/k8s-device-plugin
  version: 0.14.2
- name: opentelemetry-operator
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.37.1
- name: reloader
  repository: https://stakater.github.io/stakater-charts
  version: 1.0.48
- name: sysdig-deploy
  repository: https://charts.sysdig.com
  version: 1.26.8
digest: sha256:355b300ed6b41be3c2285a5c009a9473a1effe383ed60a85
generated: "2023-11-08T15:17:40.194274+02:00"

err: unable to update deps: no resolved dependency found for "renovate", running "helmfile deps" may resolve the issue
changing working directory back to "/Users/user/org/configuration/kubernetes"
in ./helmfile.yaml: unable to update deps: no resolved dependency found for "renovate", running "helmfile deps" may resolve the issue

```
Before this it lists env values and the helmfile itself

**Comment by yxxhero** [comment]
@jouve I can't find the root cause from the log. minimal demo will be better.

**Comment by jouve** [comment]
``` 
repositories:
  - name: bitnami
    url: docker.io/bitnamicharts
    oci: true

releases:
  - name: redis
    chart: bitnami/redis
    version: x
  - name: postgresql
    chart: bitnami/postgresql
    version: x
    installed: false
```

then `helmfile deps` 

[helmfile.log](https://github.com/helmfile/helmfile/files/13299627/helmfile.log)

**Comment by jouve** [comment]
<details>
  <summary> stack trace by adding a panic before the error </summary>
goroutine 20 [running]:
github.com/helmfile/helmfile/pkg/state.(*ResolvedDependencies).Get(0x3bacec0?, {0xc0008d0170?, 0xc0008d0168?}, {0x60d7ca0, 0x1})
        /home/cyril/work/helmfile/pkg/state/chart_dependency.go:132 +0x176
github.com/helmfile/helmfile/pkg/state.resolveDependencies(0xc0009338c0, 0x7f1665f80120?, 0xc0004fa100?)
        /home/cyril/work/helmfile/pkg/state/chart_dependency.go:185 +0x2f7
github.com/helmfile/helmfile/pkg/state.updateDependencies(0xc0009338c0, {0x7f1665f80120?, 0xc0004fa100?}, 0xc00068c000, {0xc0007d0730?, 0x385e037?}, {0xc0005fa010?, 0x385e035?})
        /home/cyril/work/helmfile/pkg/state/chart_dependency.go:271 +0x186
github.com/helmfile/helmfile/pkg/state.(*HelmState).updateDependenciesInTempDir(0xc0009338c0, {0x7f1665f80120, 0xc0004fa100}, 0x42830c0)
        /home/cyril/work/helmfile/pkg/state/chart_dependency.go:215 +0x19e
github.com/helmfile/helmfile/pkg/state.(*HelmState).UpdateDeps(0xc0009338c0, {0x487ee58, 0xc0004fa100}, 0xb1?)
        /home/cyril/work/helmfile/pkg/state/state.go:2403 +0x63a
github.com/helmfile/helmfile/pkg/app.(*Run).Deps(0xc000a40600, {0x4862cb8, 0xc00006b5c0})
        /home/cyril/work/helmfile/pkg/app/run.go:109 +0x8f
github.com/helmfile/helmfile/pkg/app.(*App).Deps.func1.1()
        /home/cyril/work/helmfile/pkg/app/app.go:128 +0x28
github.com/helmfile/helmfile/pkg/app.(*Run).withPreparedCharts(0xc000a40600, {0x410255d, 0x4}, {0x0, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, ...}, ...)
        /home/cyril/work/helmfile/pkg/app/run.go:99 +0x5bb
github.com/helmfile/helmfile/pkg/app.(*App).Deps.func1(0xc000a40600)
        /home/cyril/work/helmfile/pkg/app/app.go:122 +0x16c
github.com/helmfile/helmfile/pkg/app.(*App).ForEachState.func1(0x0?)
        /home/cyril/work/helmfile/pkg/app/app.go:969 +0xb0
github.com/helmfile/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func1.1(0xc00092e000?)
        /home/cyril/work/helmfile/pkg/app/app.go:1081 +0x17
github.com/helmfile/helmfile/pkg/app.processFilteredReleases(0xc0009338c0, 0xc0008cb410, 0x0?)
        /home/cyril/work/helmfile/pkg/app/app.go:1109 +0x106
github.com/helmfile/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func1(0xc0009338c0?)
        /home/cyril/work/helmfile/pkg/app/app.go:1080 +0x37
github.com/helmfile/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport.func2(0xc0009338c0)
        /home/cyril/work/helmfile/pkg/app/app.go:1091 +0x6c
github.com/helmfile/helmfile/pkg/app.(*App).visitStates.func1({0x41149f3, 0xd}, {0xc000057d88, 0x13})
        /home/cyril/work/helmfile/pkg/app/app.go:913 +0x6f8
github.com/helmfile/helmfile/pkg/app.(*App).visitStateFiles.func1()
        /home/cyril/work/helmfile/pkg/app/app.go:738 +0x2b
github.com/helmfile/helmfile/pkg/app.(*App).within(0xc000808120, {0xc000057d88, 0x13}, 0xc0008aba40)
        /home/cyril/work/helmfile/pkg/app/app.go:700 +0x254
github.com/helmfile/helmfile/pkg/app.(*App).visitStateFiles(0xc000808120, {0x0?, 0xc000093b28?}, {{0x0, 0x0, 0x0}, {{0x0, 0x0, 0x0}}, 0x0, ...}, ...)
        /home/cyril/work/helmfile/pkg/app/app.go:737 +0x36d
github.com/helmfile/helmfile/pkg/app.(*App).visitStates(0xc000808120, {0x0?, 0xc000093c20?}, {{0x0, 0x0, 0x0}, {{0x0, 0x0, 0x0}}, 0x0, ...}, ...)
        /home/cyril/work/helmfile/pkg/app/app.go:817 +0xdd
github.com/helmfile/helmfile/pkg/app.(*App).visitStatesWithSelectorsAndRemoteSupport(0xc000808120, {0x0, 0x0}, 0xc000093cb0, 0x0, {0xc000093d18, 0x1, 0x3d010a0?})
        /home/cyril/work/helmfile/pkg/app/app.go:1094 +0x3f3
github.com/helmfile/helmfile/pkg/app.(*App).ForEachState(0xc000808120, 0xc000093d28, 0xd8?, {0xc000093d18, 0x1, 0x1})
        /home/cyril/work/helmfile/pkg/app/app.go:962 +0xb7
github.com/helmfile/helmfile/pkg/app.(*App).Deps(0x4874f68?, {0x4862cb8, 0xc00006b5c0})
        /home/cyril/work/helmfile/pkg/app/app.go:121 +0xa5
github.com/helmfile/helmfile/cmd.NewDepsCmd.func1(0xc0001aee00?, {0x4102579?, 0x4?, 0x4102655?})
        /home/cyril/work/helmfile/cmd/deps.go:29 +0xfb
github.com/spf13/cobra.(*Command).execute(0xc0007d5500, {0x621d5a0, 0x0, 0x0})
        /home/cyril/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007d4000)
        /home/cyril/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0xc0001ae400?)
        /home/cyril/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.main.func1()
        /home/cyril/work/helmfile/main.go:29 +0x65
created by main.main in goroutine 1
        /home/cyril/work/helmfile/main.go:21 +0xe5
</details>

**Comment by jouve** [comment]
with the same helmfile.yaml and helmfile v0.157.0, I run helmfile template and it fetch only the chart with installed=true,

```
../helmfile/helmfile version            

▓▓▓ ../helmfile/helmfile

  Version            v0.157.0

../helmfile/helmfile template >/dev/null
Pulling docker.io/bitnamicharts/redis:x
Templating release=redis, chart=/tmp/helmfile3735039342/redis/redis/x/redis
``` 

so that seems to contradict the original issue (#1053)

**Comment by yxxhero** [comment]
@jouve thanks so much.
