### ISSUE TITLE
helmfile fails if base contains an empty array

### ISSUE THREAD

**Issue by gunzl1ng3r** [helmfile/helmfile#1147]
### Operating system

alpine:3.18

### Helmfile Version

0.158.1

### Helm Version

3.13.2

### Bug description

If a file listed under "bases:" only contains an empty element, like `values: []` validation will fail.

The reason for this is this part of the code: https://github.com/helmfile/helmfile/blob/main/pkg/policy/checker.go#L16 as the used regex only matches, if the key is followed by a `:` and space characters.

As `key: []` is valid YAML for an empty array, I think it should pass the checker.

Regards and thanks in advance,
Jan

### Example helmfile.yaml

---
bases:
  - ./bases/environments/global-values.yaml
  - ./bases/environments/{{ .Environment.Name }}.yaml

### Error message you've seen (if any)

`in ./helmfile.yaml: no top-level config keys are found in bases/environments/global-values.yaml`

### Steps to reproduce

https://github.com/helmfile/helmfile/blob/main/pkg/policy/checker.go#L16

### Working Helmfile Version

0.155.1

**Comment by yxxhero** [comment]
@gunzl1ng3r PR is welcome.
