### ISSUE TITLE
Support of current kustomize strategie

### ISSUE THREAD

**Issue by genofire** [helmfile/helmfile#1237]
### Operating system

NixOS

### Helmfile Version

v0.158.1

### Helm Version

v3.13.2

### Bug description

use `patches` instead of `patchesStrategicMerge` or `jsonPatches` 

### Example helmfile.yaml

not needed

### Error message you've seen (if any)

We got always an warning:
```
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

### Steps to reproduce

somewhere

### Working Helmfile Version

do not know

**Comment by yxxhero** [comment]
@genofire PR is welcome.

**Comment by genofire** [comment]
I understand ... maybe i will -> we should keep this issue open (instatt of close by stale bot)

**Comment by yxxhero** [comment]
@genofire welcome to post PRs for this issue. I will help you. pelase free to do that.

**Comment by yxxhero** [comment]
see: https://github.com/helmfile/chartify/blob/6acdb874c2e9aa3734c0cbc5b177a26d6b5e9a20/patch.go#L120

**Comment by nikolaik** [comment]
I'm interested in this too! Want to look at a PR for this, though not for a at least few weeks

**Comment by yxxhero** [comment]
@nikolaik assgined to you. looking forword  your PR. thanks so much.

**Comment by gllb** [comment]
Hello, keen to get it fixed, I submitted a fix. Please let me know if there is something wrong.
