### ISSUE TITLE
helmfile cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by arnoldyahad** [helmfile/helmfile#1262]
### Operating system

Ubuntu 21.10

### Helmfile Version

v0.160

### Helm Version

not relevant

### Bug description

similiar to https://github.com/helmfile/helmfile/issues/816 
We are trying to build a docker image with helmfile in it (in addition to helm and some helm plugins), but we encounter an error trying to use any binary from this repository: 

```
bash: ./helmfile : cannot execute binary file: Exec format error
```

it happens when i try to download all types of assets in the release(tried all 3 linux options, although we only need amd64)
```
curl -L https://github.com/helmfile/helmfile/releases/download/v0.160.0/helmfile_0.160.0_linux_amd64.tar.gz -o /test1
curl -L https://github.com/helmfile/helmfile/releases/download/v0.160.0/helmfile_0.160.0_linux_arm64.tar.gz -o /test2 
curl -L https://github.com/helmfile/helmfile/releases/download/v0.153.0/helmfile_0.153.0_linux_386.tar.gz -o /test3
```

**information regarding my docker image:**
```
docker image inspect myimage:777 --format '{{ .Os }}/{{ .Architecture }}'
linux/amd64
```

**information from within the docker:** 
```
uname -a
Linux argocd-repo-server-7dc8b9d4b7-rg8zw 5.10.192-183.736.amzn2.x86_64 #1 SMP Wed Sep 6 21:15:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
uname -m
x86_64
```

```
cat /etc/os-release
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
```

the only thing that did work, is using the old repos latest release (v0.144): 
https://github.com/roboll/helmfile/releases/tag/v0.144.0 
```
curl -L https://github.com/roboll/helmfile/releases/download/v0.144.0/helmfile_linux_amd64 -o ./test999 &&  chmod +x ./test999
```
after that running that binary works as expected: 
```
./test999
NAME:
   helmfile

USAGE:
   test999 [global options] command [command options] [arguments...]

VERSION:
   v0.144.0
```

but we want to use a newer version, but unfortunately we can't due to this bug. I saw that due to this issue: https://github.com/helmfile/helmfile/issues/816  there were changes in the build but it still doesnt work, i tried v0.160, v0.153, v0.145.5 

we must use this base image as its the base image of argocd v2.3.0 and we just need to bake helmfile in it (if it can be of any help this is the original dockerfile https://github.com/chatwork/dockerfiles/blob/c893bf64c8574a67c3c87575e7bf23c3cc232c19/argocd-helmfile/Dockerfile we just trying to build it with more recent argocd + helmfile, but im not sure its relevant at all to the understanding of this issue) 

### Example helmfile.yaml

none

### Error message you've seen (if any)

```
bash: ./helmfile : cannot execute binary file: Exec format error
```

### Steps to reproduce

use a dockerfile with Ubuntu 21.10 image (or this image: argoproj/argocd:v2.3.0) 

### Working Helmfile Version

v0.144.0 from the roboll repo

**Comment by yxxhero** [comment]
@arnoldyahad helmfile_0.153.0_linux_386.tar.gz? it's a tar.gz. please untar it before run it.

**Comment by yxxhero** [comment]
@arnoldyahad if you have no more issue. please close this one.

**Comment by arnoldyahad** [comment]
@yxxhero thanks for pointing that out, this is a change from the  last release of previous repo that didn't tar the releases ( https://github.com/roboll/helmfile/releases/tag/v0.144.0 ) and the first release in this repo didn't mention that change (https://github.com/helmfile/helmfile/releases/tag/v0.145.0) 

whoever had a dockerfile (from argocd-helmfile or any other source) that downloaded argocd-helmfile from the previous repo like this:
```
curl -o /usr/local/bin/helmfile -L https://github.com/roboll/helmfile/releases/download/${HELMFILE_VERSION}/helmfile_linux_amd64
chmod +x /usr/local/bin/helmfile
```

needs to edit it and use it like its here for it to work:
https://github.com/chatwork/dockerfiles/blob/master/argocd-helmfile/Dockerfile
