### ISSUE TITLE
Helmfile does not work in offline mode (--skip-deps) after all relevant helm charts have been cached

### ISSUE THREAD

**Issue by strainovic** [helmfile/helmfile#1317]
### Operating system

Windows 11 (Git Bash)

### Helmfile Version

0.161.0

### Helm Version

v3.13.3

### Bug description

I'm trying to use helmfile in offline mode based on https://helmfile.readthedocs.io/en/latest/#running-helmfile-without-an-internet-connection.

Initially, I ran a command without `--skip-deps` to pull all helm repository indices and helm charts locally, and after that, I disconnected from the network.

In the local helm cache, I have the required helm chart.

![image](https://github.com/helmfile/helmfile/assets/10864240/448ac5bc-dec8-4d8a-a23c-a554a78cf5e5)

It behaves the same for any other command such as `apply`, `diff`, and `template`. Is this a helmfile or helm issue?

https://github.com/helm/helm/issues/12602

Thanks

### Example helmfile.yaml

not relevant

### Error message you've seen (if any)

Upgrading release=configuration, chart=platform/configuration

FAILED RELEASES:
NAME            CHART                    VERSION   DURATION
configuration   platform/configuration                   1s

in ./helmfile.yaml: failed processing release configuration: command "C:\\ProgramData\\chocolatey\\bin\\helm.exe" exited with non-zero status:

PATH:
  C:\ProgramData\chocolatey\bin\helm.exe

ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: configuration (13 bytes)
  4: platform/configuration (22 bytes)
  5: --version (9 bytes)
  6: 1.13.6 (6 bytes)
  7: --wait (6 bytes)
  8: --timeout (9 bytes)
  9: 600s (4 bytes)
  10: --cleanup-on-fail (17 bytes)
  11: --namespace (11 bytes)
  12: dev (11 bytes)
  13: --values (8 bytes)
  14: C:\Users\NENAD~1.STR\AppData\Local\Temp\helmfile1087538063\dev-configuration-values-d787d58b7 (101 bytes)
  15: --values (8 bytes)
  16: C:\Users\NENAD~1.STR\AppData\Local\Temp\helmfile1286928203\dev-configuration-values-849f69675 (101 bytes)
  17: --values (8 bytes)
  18: C:\Users\NENAD~1.STR\AppData\Local\Temp\helmfile2671782362\dev-configuration-values-6f8574b954 (102 bytes)
  19: --values (8 bytes)
  20: C:\Users\NENAD~1.STR\AppData\Local\Temp\helmfile181973588\dev-configuration-values-7d97ccf666 (101 bytes)
  21: --values (8 bytes)
  22: C:\Users\NENAD~1.STR\AppData\Local\Temp\helmfile1256527610\dev-configuration-values-56c4984b69 (102 bytes)
  23: --reset-values (14 bytes)
  24: --history-max (13 bytes)
  25: 1 (1 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Get "https://remote-repo/chartrepo/platform/charts/configuration-1.13.6.tgz": dial tcp: lookup remote-repo: getaddrinfow: The requested name is valid, but no data of the requested type was found.

COMBINED OUTPUT:
  Error: Get "https://remote-repo/chartrepo/platform/charts/configuration-1.13.6.tgz": dial tcp: lookup remote-repo getaddrinfow: The requested name is valid, but no data of the requested type was found.

### Steps to reproduce

I replaced the real helm repository hostname with `remote-repo` due to privacy.

### Working Helmfile Version

uknown

**Comment by yxxhero** [comment]
@strainovic PR is welcome.

**Comment by strainovic** [comment]
This appears to be the Helm bug, so I'm closing this one.

https://github.com/helm/helm/issues/12893

Thanks
