### ISSUE TITLE
Typo in helm plugin install prompt "The helm plugin %s is not installed, do you need to install it"

### ISSUE THREAD

**Issue by wallrj** [helmfile/helmfile#1350]
### Operating system

Ubuntu

### Helmfile Version

master

### Helm Version

latest

### Bug description

The following prompt is confusing because:
* I assume I do **need** to install it otherwise why would helmfile ask me.
* it's not clear that whether "plugin secrets" or plugin "secrets" is missing.
* missing question mark at the end of the question.

> The helm plugin secrets is not installed, do you need to install it [y/n]:

It should say:
> The helm plugin ~~secrets~~ **'secrets'** is not installed, do you ~~need~~**want** to install it **?** [y/n]:

https://github.com/helmfile/helmfile/blob/268a4808e98164bf4f88d1509c8f083f2c9f9859/pkg/app/init.go#L174

### Example helmfile.yaml

NA

### Error message you've seen (if any)

NA

### Steps to reproduce

NA

### Working Helmfile Version

NA

**Comment by yxxhero** [comment]
@wallrj PR is welcome.
