### ISSUE TITLE
If a `helmfile.lock` exists, you must use the exact version of the Helmfile binary specified in this file’s `version`

### ISSUE THREAD

**Issue by JuryA** [helmfile/helmfile#1473]
### Operating system

Ubuntu 22.04.4 LTS

### Helmfile Version

v0.162.0

### Helm Version

v3.14.2

### Bug description

**If a `helmfile.lock` exists and the `helmfile` binary version is older than specified in the `version` key, using `helmfile apply/sync` will result in an error, as shown below, even though the configuration could be deployed (it is compatible with a higher version of Helmfile).**

## Dirty Workaround

The problem can be mitigated easily using `helmfile deps`, but this is not always appropriate, especially when many repositories are involved. Typically, changing the `version` key in the `helmfile.lock` to match the current version of the `helmfile` being used is sufficient, although it is neither elegant nor technically correct. However, in most cases, this works fine because changes in the Helmfile API that affect the lock file are infrequent and rare.

## Possible Solutions

From this perspective, there are essentially two possible solutions (or variations thereof): **Relaxation of version verification** and **Delaying the error** until an API incompatibility causes a failure. Personally, I would lean towards a combination of both, as it offers the safest approach.

### Relaxation of Version Verification with Error Delay

In my opinion, it is unnecessary to verify the `helmfile` binary version against the `helmfile.lock`. Examining other tools that implement some form of dependency locking, we find that **npm**, **yarn**, **cargo** do not store the version of the binary that created the lock file at all; **go** has a directive `go` in `go.mod` specifying the minimum version of `go`, but they have an internal mechanism that—if a lower version of `go` is used—can update to the required version with minimal effort. Since Helmfile lacks such an option (it can only detect if a newer version exists, but the user must manually download and update it), I personally think that recording the version but not enforcing it would be a better approach. Perhaps displaying a warning, but allowing the deployment to continue until a failure occurs would be a fine compromise. If a failure occurs, print the actual error message indicating that this was (probably) caused by version incompatibility. If no failure occurs, then there is no reason to enforce the installation of a higher version of Helmfile.

## Conclusion

The proposed solution has its reasons, which I can describe in detail if this topic is opened for further discussion. In my humble opinion, however, the current solution is worse in terms of UX than the proposed solution above, and the risks related to a breaking change, which could arise, are so minor that they can be addressed during the process as they occur.

@mumoshu @yxxhero WDYT?

### Example helmfile.yaml

any

### Error message you've seen (if any)

`in helmfile.d/helmfile.yaml.gotmpl: in .helmfiles[1]: in ../helmfile.master.yaml: [unable to resolve 1 deps: the lockfile was created by Helmfile v0.163.0, which is newer than current v0.162.0; Please upgrade to Helmfile v0.163.0 or greater]`

### Steps to reproduce

1) Create `helmfile.lock` with `helmfile deps`
2) Use `helmfile apply` with older `helmfile` binary

### Working Helmfile Version

none

**Comment by mumoshu** [comment]
@JuryA Hi! I much appreciate your proposal.

> recording the version but not enforcing it would be a better approach

I fully agree with this approach!

We can relax it now, and later (1)add the current validation back only after we are to introduce any backward-incompatible changes, OR (2)ensure the entire helmfile.lock is modified automatically to adapt to the latest schema.
