### ISSUE TITLE
template output-dir repeated usage duplicate values

### ISSUE THREAD

**Issue by sstarcher** [helmfile/helmfile#1484]
### Operating system

Ubuntu 20.24

### Helmfile Version

161.0

### Helm Version

3.14.1

### Bug description

 helmfile template \
        --include-crds \
        --skip-tests \
        -f ""helmfile.yaml" \
        --output-dir "${OUTPUT_DIR}"/ \
        --output-dir-template="{{ .OutputDir }}/releases/{{ .Release.Name }}"

Running the command the first time you get all of the correct outputs to OUTPUT_DIR.  If you run it a second time while the files already exist the vast majority of them are identical, but a few resource types get duplicated where the values get appended.  Each subsequent time you run helmfile template it adds to the existing file instead of replacing it with the output of helmfile template.

This seems to be happening for any resource that contains a `helm.sh/hook`, but not resources without a helm.sh/hook reference.

### Example helmfile.yaml

N/A

### Error message you've seen (if any)

N/A

### Steps to reproduce

template out files with a helm hook multiple times to the same folder

### Working Helmfile Version

N/A

**Comment by sstarcher** [comment]
Root issue looks to be a helm issue feel free to close this https://github.com/helm/helm/issues/12988

**Comment by yxxhero** [comment]
@sstarcher Thanks for your issue.
