### ISSUE TITLE
Helmfile fails with `the version for OCI charts should be semver compliant, the latest tag is not supported anymore for helm >= 3.8.0`

### ISSUE THREAD

**Issue by zchenyu** [helmfile/helmfile#1541]
### Operating system

Ubuntu 22.04

### Helmfile Version

0.162.0

### Helm Version

v3.11.0

### Bug description

If I omitted the chart version from my helmfile, it fails with `the version for OCI charts should be semver compliant, the latest tag is not supported anymore for helm >= 3.8.0`

According to Helm docs, I expect this to pull the latest stable version of the chart from the OCI registry: https://helm.sh/docs/helm/helm_install/
This doesn't seem to be an issue for non-OCI repositories.

### Example helmfile.yaml

```
releases:
  - name: foo
    chart: oci://registry/chart
```

### Error message you've seen (if any)

`the version for OCI charts should be semver compliant, the latest tag is not supported anymore for helm >= 3.8.0`

### Steps to reproduce

N/A

### Working Helmfile Version

0.162.0

**Comment by yxxhero** [comment]
@zchenyu 
`chart: oci://registry/chart` start with oci. so you are using oci chart.

**Comment by zchenyu** [comment]
Yes that's correct. I'm expecting Helm / helmfile to pull from the latest OCI chart.
If that's not possible, maybe we should document this behavior somewhere?

**Comment by yxxhero** [comment]
@zchenyu why do't set the version? you can set latest for the version.

**Comment by tropnikovvl** [comment]
The `latest` version doesn't work, I get exactly the same error when I try to pull the `latest` helm chart from the ECR

**Comment by zchenyu** [comment]
I'm currently working around this by specifying `^1.0.0`
