### ISSUE TITLE
debug flag not used in helm template

### ISSUE THREAD

**Issue by zanettea** [helmfile/helmfile#1586]
### Operating system

Ubuntu 20

### Helmfile Version

0.165

### Helm Version

3.12.1

### Bug description

Even if "--debug" flag is set to helmfile, running the template command on a wrong template the result says:

```
OUTPUT:
  Error: YAML parse error on chart/templates/template.yaml: error converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context
  Use --debug flag to render out invalid YAML]
changing working directory back to "/tmp/helmfile"
in ./helmfile.yaml: [exit status 1

COMMAND:
  helm template --debug=false --output-dir=/tmp/chartify4181764224/prometheus/prom-norbac-ubuntu/helmx.1.rendered prom-norbac-ubuntu /tmp/chartify4181764224/prometheus/prom-norbac-ubuntu --set rbac.create=false --namespace prometheus
```

### Example helmfile.yaml

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: ./chart

### Error message you've seen (if any)

COMMAND:
  helm template --debug=false --output-dir=/tmp/chartify2979750007/prometheus/prom-norbac-ubuntu/helmx.1.rendered prom-norbac-ubuntu /tmp/chartify2979750007/prometheus/prom-norbac-ubuntu --namespace prometheus

OUTPUT:
  Error: YAML parse error on chart/templates/template.yaml: error converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context
  Use --debug flag to render out invalid YAML]

### Steps to reproduce

https://github.com/zanettea/helmfile-bug

### Working Helmfile Version

0

**Comment by yxxhero** [comment]
@zanettea PR is welcome.
