### ISSUE TITLE
how to not use the default values.yaml file by default?

### ISSUE THREAD

**Issue by Diliz** [helmfile/helmfile#1591]
### Operating system

all

### Helmfile Version

all

### Helm Version

latest

### Bug description

I have a values.yaml file in my helm chart where I want to include a key that is templated, as follows:
```yaml
mykey: true
{{ .testing }}: true
```
I tpl the content of this values and inject it in the releases values:
```
{{ $values := readFile "values.yaml" | fromYaml }}
{{ $values  = tpl $values (dict "testing" "mycustomvalue") }}
...
releases:
 - name: myrelease
   ...
   values:
     - {{- $values | toYaml | nindent 8 }}
```

The merged values will looks like this:
```
mykey: true
mycustomvalue: true
{{ .testing }}: true
```

It happens since `{{ .testing }}` is not the same key as `mycustomvalue`, I was thinking the values I setted to replace the values.yaml file, is there any way to handle this without moving values.yaml file myself ?

(I already did a mv command in helmfile, but if I can avoid moving files with the mv command in my helmfile.yaml file, it should be better)

### Example helmfile.yaml

not needed

### Error message you've seen (if any)

none

### Steps to reproduce

none

### Working Helmfile Version

none

**Comment by yxxhero** [comment]
@Diliz the answer is not.

**Comment by Diliz** [comment]
> @Diliz the answer is not.

I was just trying to replace a key in a dictionnary, was thinking it was maybe something that was bothering other people :)
