### ISSUE TITLE
Unable to build: checksum mismatch when `GOPROXY=direct`

### ISSUE THREAD

**Issue by unlimitedsola** [helmfile/helmfile#1636]
### Operating system

Fedora 40

### Helmfile Version

git main

### Helm Version

not relevant

### Bug description

Building the code on the `main` branch (369ad70b22ce4cab324bf1cdba51570fd010e5e9 at the time this issue is filed) results checksum mismatch error when `GOPROXY` is set to `direct`.

### Example helmfile.yaml

not relevant

### Error message you've seen (if any)

```
verifying github.com/helmfile/vals@v0.37.3: checksum mismatch
        downloaded: h1:bhzAJx78Yoh0VJz0rMWvrRwhg6zPzuSUt2xy0mk3M0A=
        go.sum:     h1:5X9zRv8NT7UnJOtKBk4gA/cpfE25kBq/9v7URKv62Uo=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

### Steps to reproduce

doesn't fit, please see comment below

### Working Helmfile Version

not yet verified

**Comment by unlimitedsola** [comment]
### Steps to reproduce

1. Have a clean golang workspace, or have modcache cleaned: `go clean -modcache`
2. Set `GOPROXY` to `direct`: `go env -w GOPROXY=direct`
3. Run `go build`

**Comment by yxxhero** [comment]
@unlimitedsola maybe github.com/helmfile/vals@v0.37.3 is be retaged in the past.
