### ISSUE TITLE
 Registry password printed to stderr when configuring repositories in helmfile.yaml on error

### ISSUE THREAD

**Issue by LucaHennart** [helmfile/helmfile#1669]
### Operating system

macOS Sonoma Version 14.6 (23G80)

### Helmfile Version

v0.167.1

### Helm Version

version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.21.5"}

### Bug description

When using a non-OCI-compliant registry (`repositories[].oci:false`), and when relying on authentication provided via the `repositories:` block or environment variables, it seems that on a failure case, the credentials are shown in plaintext in stderr.

I would expect the credentials to be either:
1. Provided via stdin, as already done when pointing to an OCI compliant registry.
See https://github.com/helmfile/helmfile/issues/1274 and its [related fix](https://github.com/helmfile/helmfile/pull/1275) when `oci=true`

2. Sanitized in the output, as already done for `--set` overrides.
See https://github.com/helmfile/helmfile/issues/886

### Example helmfile.yaml

```
$ cat helmfile.yaml
helmBinary: helm3

helmDefaults:
  kubeContext: <context>

repositories:
  - name: foo-charts
    url: https://<url>/repository/helm/

releases:
  - name: dummy-app-2
    namespace: spinnaker
    chart: foo-charts/chart
    version: 13.0.0
```

### Error message you've seen (if any)

```
$ FOO_CHARTS_PASSWORD=xxx FOO_CHARTS_USERNAME=yyy helmfile template
Adding repo foo-charts https://<url>/repository/helm/
in ./helmfile.yaml: command "/Users/<user>/.local/bin/helm3" exited with non-zero status:

PATH:
  /Users/<username>/.local/bin/helm3

ARGS:
  0: helm3 (5 bytes)
  1: --kube-context (14 bytes)
  2: <context> (17 bytes)
  3: repo (4 bytes)
  4: add (3 bytes)
  5: foo-charts (13 bytes)
  6: https://<url>/repository/helm/ (xx bytes)
  7: --force-update (14 bytes)
  8: --username (.. bytes)
  9: yyy (8 bytes)
  10: --password (.. bytes)
  11: xxx (3 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: looks like "https://<url>/repository/helm/" is not a valid chart repository or cannot be reached: failed to fetch https://<url>/repository/helm/index.yaml : 401 Unauthorized

COMBINED OUTPUT:
  Error: looks like "https://<url>/repository/helm/" is not a valid chart repository or cannot be reached: failed to fetch https://<url>/repository/helm/index.yaml : 401 Unauthorized

```

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@LucaHennart thanks so much. we will improve this issue.

**Comment by LucaHennart** [comment]
Thanks for the fix!
