### ISSUE TITLE
Distribution of releases

### ISSUE THREAD

**Issue by tigerquoll** [helmfile/helmfile#171]
### Discussed in https://github.com/helmfile/helmfile/discussions/119

<div type='discussions-op-text'>

<sup>Originally posted by **samuelsayag** May 29, 2022</sup>
Hello,

Would it be possible to have the helmfile binaries distributed like in the old repository and not just having sources?

LIke this:

![image](https://user-images.githubusercontent.com/6291619/170856978-9da84409-0178-4cbd-a7d1-1e0521d385a5.png)

Thanks!</div>

**Comment by eperdeme** [comment]
It's breaking functions such as https://github.com/feniix/asdf-helmfile/issues/4

**Comment by yxxhero** [comment]
@eperdeme @tigerquoll It will be published in the near future.
