### ISSUE TITLE
isFile / readFile not defined

### ISSUE THREAD

**Issue by a-nicolae** [helmfile/helmfile#1713]
### Operating system

MacOS 14.6.1

### Helmfile Version

v0.168.0

### Helm Version

3.16.1

### Bug description

Hey there! Templating functions don't seem to work for me, the error is function "isFile" not defined. I checked in the go code for release 0.168.0 and the functions are there and should work.

### Example helmfile.yaml

Basically, I'm trying to make sure that the sealed secret file exists:
```
{{ if isFile (printf "environments/secret.xyz.%s.%s.encrypted.yaml" .Values.dataCenterName .Values.environment) }}

{{ end }} 
```

### Error message you've seen (if any)
```
Error: parse error at (stackgres-secrets/templates/sealedsecret-xyz.yaml:1): function "isFile" not defined
  helm.go:86: 2024-09-19 17:22:54.12293 +0300 EEST m=+0.018077085 [debug] parse error at (stackgres-secrets/templates/sealedsecret-xyz.yaml:1): function "isFile" not defined
```
### Steps to reproduce

-

### Working Helmfile Version

-

**Comment by yxxhero** [comment]
@a-nicolae move helmfile.yaml to helmfile.yaml.gotmpl

**Comment by yxxhero** [comment]
@a-nicolae pelase post an example. thanks so much.

**Comment by yxxhero** [comment]
@a-nicolae it look like helm issue.
so please create an demo in github then I can debug it.

**Comment by yxxhero** [comment]
@a-nicolae ping

**Comment by a-nicolae** [comment]
@yxxhero pong! Sorry, I wasn't around yesterday. 
I tried with mv helmfile.yml helmfile.yaml.gotmpl, but nothing changed.
Here's the repo for testing, still throws for me   Error: parse error at (stackgres-secrets/templates/namespace.yml:1): function "isFile" not defined:

 https://github.com/a-nicolae/test-helmfile

**Comment by yxxhero** [comment]
@a-nicolae https://github.com/a-nicolae/test-helmfile/tree/main/secrets   this is a helm chart. isFile is only for helmfile state file, not chart file.

**Comment by a-nicolae** [comment]
Ohhhh, I got it now. Thanks! I will close this.
