### ISSUE TITLE
allow to run helmfile template without updating repos

### ISSUE THREAD

**Issue by sstarcher** [helmfile/helmfile#1728]
### Operating system

Ubuntu 20.24

### Helmfile Version

0.166.0

### Helm Version

3.15.3

### Bug description

This change had fixed this issue for me https://github.com/helmfile/helmfile/issues/526, but it was removed for local charts with https://github.com/helmfile/helmfile/pull/541.

The main issue is that I want to be able to run `helmfile` multiple times in parallel, but `helm repos update` can not be ran concurrently.  Once they add a lock this would not break, but it would still be much slower than desired as I can prerun all of the repos and not being able to do --skip-refresh will show it down.

### Example helmfile.yaml

N/A

### Error message you've seen (if any)

```
  Error: error loading /home/coder/.cache/helm/repository/bitnami-index.yaml: empty index.yaml file]
```

### Steps to reproduce

helmfile does not allow for specifying --skip-refresh for templating for local charts

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@sstarcher PR is welcome.

**Comment by sstarcher** [comment]
Would you accept a PR that adds support for `--skip-refresh` to `helmfile template`?

**Comment by zhaque44** [comment]
yes @sstarcher that would be good

**Comment by yxxhero** [comment]
> Would you accept a PR that adds support for `--skip-refresh` to `helmfile template`?

sound good. feel free to do that.

**Comment by sstarcher** [comment]
https://github.com/helmfile/helmfile/pull/1736
