### ISSUE TITLE
helmfile template fails with passed --args

### ISSUE THREAD

**Issue by baurmatt** [helmfile/helmfile#1749]
### Operating system

MacOS 14.5

### Helmfile Version

v0.169.1

### Helm Version

v3.16.2

### Bug description

helmfile template fails if args are passed which aren't compatible with `helm dependency build`:

```
helmfile template --args --dry-run=server --validate --output-dir /tmp/build
```

`--args --dry-run=server` is required to use helm lookup with `helm template`.
 
This seems to only happened when using multiple helmfile in a helmfile.d directory. At least I was able to reproduce this with a single helmfile.yaml

### Example helmfile.yaml

```
mkdir helmfile-reproduce && cd helmfile-reproduce
mkdir helmfile.d
tee helmfile.d/foo.yaml << END
releases:
- name: foo
  chart: ../foo
END
cp helmfile.d/foo.yaml helmfile.d/bar.yaml
mkdir -p foo/templates/
tee foo/Chart.yaml << END
apiVersion: v2
name: foo
description: A chart to deploy foo
type: application
version: 0.1.0
END
```

### Error message you've seen (if any)

```
Building dependency release=foo, chart=../foo
in helmfile.d/foo.yaml: [building dependencies of local chart: command "/opt/homebrew/bin/helm" exited with non-zero status:

PATH:
  /opt/homebrew/bin/helm

ARGS:
  0: helm (4 bytes)
  1: dependency (10 bytes)
  2: build (5 bytes)
  3: ../foo (6 bytes)
  4: --dry-run=server (16 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unknown flag: --dry-run

COMBINED OUTPUT:
  Error: unknown flag: --dry-run]
```

### Steps to reproduce

See example helmfile.yaml

### Working Helmfile Version

-

**Comment by yxxhero** [comment]
https://github.com/helmfile/helmfile/blob/main/docs/proposals/towards-1.0.md#remove-the---args-flag-from-the-helmfile-command

**Comment by baurmatt** [comment]
@yxxhero Thanks! :) So you're suggesting to add an additional parameter `--template-args` for `helmfile template`?

What makes me wonder is, that the `helmfile template` command only fails on multiple helmfiles in a helmfile.d directory, with a single helmfile this isn't a problem. It seems to me that somewhere in the code `--args` get's reused while it shouldn't.

**Comment by baurmatt** [comment]
Found it! extra args doesn't get reset before running `dependency build` and is thus polluted from the command executions before.

**Comment by baurmatt** [comment]
Well, this fixed it for helmfiles with one release using Helm lookup in a helmfile.d directory. But my change broke it for helmfiles with multiple releases using Helm lookup 😭
