### ISSUE TITLE
Helmfile cmd not overriding string value in chart-values.yaml file

### ISSUE THREAD

**Issue by pritpambhar** [helmfile/helmfile#1801]
### Operating system

Red Hat Enterprise Linux 9.3

### Helmfile Version

v.0.161.0

### Helm Version

v3.14.4

### Bug description

I am using this `helmfile.yaml` which has multiple charts details as mentioned below and I am deploying charts through `helmfile` command. I have below properties of redis chart in `helmfile.yaml`. When I am doing this I am getting error as mentioned under ERROR section. But when I am trying `helm upgrade` with `--set-string sentinel.service.nodePorts.redis="32110"` its working as expected. How can I achieve same within `helmfile.yaml` without explicitly using `--set-string` argument.

I have tried using the `{{"32110" | quote}}`, `!!string {{ "32110" }}`, `!!str{{"32110"}}`, `"{{32110}}"`, etc..  but encountering the same error for all of them.

```
sentinel.service.type=NodePort
sentinel.service.nodePorts.redis="32110"
sentinel.service.nodePorts.sentinel="32456"
```

### Example helmfile.yaml

```
- name: redis
  namespace: {{ .Values.APPLICATION_NAMESPACE }}
  chart:  charts/redis-20.1.5.tgz
  wait: true
  waitForJobs: true
  timeout: 300
  set:
  - name: serviceAccount.create
    value: false
  - name: serviceAccount.name
    value: "xxx-external"
  - name: sentinel.service.type
    value: NodePort
  - name: sentinel.service.nodePorts.redis
    value: !!str{{"32110"}}
  - name: sentinel.service.nodePorts.sentinel
    value: !!str{{"32456"}}
  values:
  - values-files/redis-values.yaml
```

### Error message you've seen (if any)

ERROR :- 

```
- sentinel.service.nodePorts.redis: Invalid type. Expected: string, given: integer
- sentinel.service.nodePorts.sentinel: Invalid type. Expected: string, given: integer
```

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
see: https://github.com/roboll/helmfile/issues/608

**Comment by pritpambhar** [comment]
@yxxhero Out of all possible solution `!!str{{"30100"}}` is the only one which is not throwing error but although it is not overriding the value present in `chart-values.yaml`.
Also in the suggested issue they are using env variable but for me, I have to use hardcoded values like "30100"

**Comment by pritpambhar** [comment]
@yxxhero Apologize but didn't get you. All I am using is below command to execute `helmfile.yaml`.

```
helmfile --file "${EXECUI_DIR}/charts/helmfile.yaml" --environment default ${HELMFILE_SELECTOR_ARGS} sync ${HELM_COMMAND_EXTRA_ARGS} \
  --values "${VALUES_GLOBAL_FILE}" $* 2>&1 | tee -a "${LOGFILE}"
```

**Comment by pritpambhar** [comment]
@yxxhero No problem. Yes I got you now.

While using `--set` with `helm`, I am getting the same result that is error. But its working perfectly when using `--set-string` with `helm`. I am getting the desired output when using this argument.

**Comment by yxxhero** [comment]
@pritpambhar oh. I got the reason.

**Comment by yxxhero** [comment]
@pritpambhar --state-values-set-string

set state STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2). Used to override .Values within the helmfile template (not values template).

**Comment by pritpambhar** [comment]
@yxxhero So you mean to say I should use cmd something like mentioned below?

```
helmfile --file "${EXECUI_DIR}/charts/helmfile.yaml" --environment default ${HELMFILE_SELECTOR_ARGS} sync \
  --values "${VALUES_GLOBAL_FILE}" --state-values-set-string sentinel.service.nodePorts.redis="30100",sentinel.service.nodePorts.sentinel="32456" ${HELM_COMMAND_EXTRA_ARGS} $* 2>&1 | tee -a "${LOGFILE}"
```

If Yes, then it might be overriding the `helmfile.yaml`, but still it is not overriding the values present in `chart-values.yaml`

**Comment by pritpambhar** [comment]
@yxxhero And just FYI, I am getting those issues while deploying redis chart from bitnami. So when I am mentioning `chart-values.yaml` it is actually `redis-values.yaml` .

**Comment by yxxhero** [comment]
@pritpambhar got it. new feature.
