### ISSUE TITLE
No option to open bug report

### ISSUE THREAD

**Issue by raxod502-plaid** [helmfile/helmfile#192]
When clicking `New issue` there is no option to open a bug report:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/69264599/176539021-9d12e156-f08b-4c3a-943a-1049810791d7.png">

This is presumably because of the following error message at https://github.com/helmfile/helmfile/blob/main/.github/ISSUE_TEMPLATE/bug.yml as a result of https://github.com/helmfile/helmfile/pull/134.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/69264599/176538943-a094f856-83b2-48ac-90ff-b2b23b86ee81.png">

**Comment by yxxhero** [comment]
@mumoshu Thanks very much.

**Comment by mumoshu** [comment]
@raxod502-plaid Thanks a lot for reporting! This has been fixed via #198
