### ISSUE TITLE
Incompatible with latest helm-secrets

### ISSUE THREAD

**Issue by raxod502-plaid** [helmfile/helmfile#193]
@jkroepke mentioned in https://github.com/roboll/helmfile/issues/1878#issuecomment-860043605 an upcoming change in helm-secrets which would break helmfile, which has since been released and breaks helmfile. I think the following code section needs to be updated to correspond to the newer helm-secrets behavior that was described in the linked comment: https://github.com/helmfile/helmfile/blob/9dca4fea5926c2ae4266e4ac1cad3b72ef9afed9/pkg/helmexec/exec.go#L282-L294

With the current code, an error occurs whenever using helmfile with helm-secrets and a custom `HELM_SECRETS_DEC_SUFFIX` and helm-secrets 3.8.2.

Repro: https://github.com/raxod502-plaid/helmfile-issue-1

In that repo with
* helm 3.3.4
* helm-secrets 3.8.2
* helmfile 0.144.0

Then if I run `helmfile template` it works:

```
% helmfile template
Decrypting secret /Users/rrosborough/temp/helmfile-repro/secrets.yaml
[helm-secrets] Decrypting /Users/rrosborough/temp/helmfile-repro/secrets.yaml

Building dependency release=hewwo, chart=hewwo
Templating release=hewwo, chart=hewwo
```

However if I use a custom decryption suffix it is broken:

```
% HELM_SECRETS_DEC_SUFFIX=.dec helmfile template
Decrypting secret /Users/rrosborough/temp/helmfile-repro/secrets.yaml
[helm-secrets] Decrypting /Users/rrosborough/temp/helmfile-repro/secrets.yaml

open /Users/rrosborough/temp/helmfile-repro/secrets.dec: no such file or directory
open /Users/rrosborough/temp/helmfile-repro/secrets.dec: no such file or directory
in ./helmfile.yaml: failed to read helmfile.yaml: failed loading environment secrets with 1 errors
```

Furthermore, the file `secrets.yaml.dec` is created in the repo and is not cleaned up. It seems that helmfile and helm-secrets are in disagreement about the name of the decrypted file.

Note that this worked back in helm-secrets 3.7.0-dev, but it's broken in 3.8.2 due to the aforementioned upstream update.

Using `HELM_SECRETS_DEC_SUFFIX` is required for our use case due to https://github.com/roboll/helmfile/issues/1878#issuecomment-860043605 to which there does not appear to be another workaround at present.

**Comment by raxod502-plaid** [comment]
A workaround is to use a suffix other than `.yaml` on your secrets file. We renamed our secrets files from `.yaml` to `.yml` and it works fine, albeit looking very silly.

**Comment by philomory** [comment]
I think maybe a better way to resolve this would be to avoid decrypting secrets files to a decrypted file at all; it would probably be better to simply capture the stdout of `helm secrets view`, than to run `helm secrets dec`, work out the path to the decrypted file, read it, and then delete it manually.

**Comment by philomory** [comment]
I think something like this would do it, though I haven't tested it yet:
```diff
diff --git a/pkg/helmexec/exec.go b/pkg/helmexec/exec.go
index dc1668c..ca52d05 100644
--- a/pkg/helmexec/exec.go
+++ b/pkg/helmexec/exec.go
@@ -281,38 +281,14 @@ func (helm *execer) DecryptSecret(context HelmContext, name string, flags ...str
                helm.logger.Infof("Decrypting secret %v", absPath)
                preArgs := context.GetTillerlessArgs(helm)
                env := context.getTillerlessEnv()
-               out, err := helm.exec(append(append(preArgs, "secrets", "dec", absPath), flags...), env)
-               helm.info(out)
+               secretBytes, err := helm.exec(append(append(preArgs, "secrets", "view", absPath), flags...), env)
                if err != nil {
                        secret.err = err
                        return "", err
                }

-               // HELM_SECRETS_DEC_SUFFIX is used by the helm-secrets plugin to define the output file
-               decSuffix := os.Getenv("HELM_SECRETS_DEC_SUFFIX")
-               if len(decSuffix) == 0 {
-                       decSuffix = ".yaml.dec"
-               }
-
-               // helm secrets replaces the extension with its suffix ONLY when the extension is ".yaml"
-               var decFilename string
-               if strings.HasSuffix(absPath, ".yaml") {
-                       decFilename = strings.Replace(absPath, ".yaml", decSuffix, 1)
-               } else {
-                       decFilename = absPath + decSuffix
-               }
-
-               secretBytes, err := os.ReadFile(decFilename)
-               if err != nil {
-                       secret.err = err
-                       return "", err
-               }
                secret.bytes = secretBytes

-               if err := os.Remove(decFilename); err != nil {
-                       return "", err
-               }
-
        } else {
                // Cache hit
                helm.logger.Debugf("Found secret in cache %v", absPath)
```

**Comment by yxxhero** [comment]
@philomory Can you create a PR. reveiw it toghter.Thanks very much.

**Comment by IkePCampbell** [comment]
Sadly glad we arent the only ones affected by this, any update?

**Comment by philomory** [comment]
Still waiting on review for PR#201, once that's merged this should be addressed AFAIK.
