### ISSUE TITLE
helm upgrade flag "--reuse-values" via ARGS has no effect

### ISSUE THREAD

**Issue by Hamdiovish** [helmfile/helmfile#221]
### Operating system

Ubuntu 18.04 LTS

### Helmfile Version

0.145.2

### Helm Version

v3.9.0

### Bug description

Passing the helm upgrade flag "--reuse-values" via the "--args" option to "helmfile sync" and "helmfile apply" has no effect.

Example:
This is a simple helm chart containing one config-map with two values "first_name" and "last_name".
We want to update these values using helmfile following the steps below:

The content of "staging-values-01.yaml":
```
first_name: "spring"
last_name: "boot"
```

The content of "staging-values-02.yaml":
```
last_name: "mvc"
```

1. Run helmfile for the 1st time:
>helmfile -f helmfile.yaml sync --values staging-values-01.yaml

As expected, "first-name" will be "spring" and "last_name" will be "boot".

2. ReRun helmfile with different values:

>helmfile -f helmfile.yaml sync --values staging-values-02.yaml --args "--reuse-values"

Let say we want to update only the "last_name" and we omitted "first_name" from the values.yaml since we expect that it will remain the same:

What happens after running the command is that the "last_name" is updated, but the "first_name" which is removed in the "staging-values-02.yaml" has been restored to the default value of the chart instead of remaining at the previous value.

So instead of having "first_name: spring" and "last_name: mvc", we got "fist_name: lorem" and "last_name: mvc"

We observed the same behaviour with "helmfile sync" and "helmfile update".

Otherwise, in case this is expected, how to achieve the desired result of updating only a subset of values, the behavior of "--reuse-values", using helmfile args/options.

### Example helmfile.yaml

releases:
- name: simple-chart
  namespace: staging
  chart: ./simple-chart

### Error message you've seen (if any)

There is no error message but the result of the execution is not as expected.

### Steps to reproduce

https://github.com/Hamdiovish/helmfile-args-report

**Comment by yxxhero** [comment]
@Hamdiovish Does this problem exist in version 0.144.0?

**Comment by yxxhero** [comment]
@Hamdiovish I will  try to see this issue. Thanks very much.

**Comment by yxxhero** [comment]
-args isn't a fully supported feature because we aren't sure which args should be passed to which helm command(s) helmfile is running.

**Comment by Hamdiovish** [comment]
@yxxhero thank you for your prompt,
Actually yes, it’s happening for 0.144.x and 0.143.x too.

In this case of “-args” is not fully supported, how can we achieve the behavior of helm arg “—reuse-values” in helmfile context properly and in clean way?

I’m saying “properly and in clean way” because I found a workaround which is based on using “helm he values [release] > current_values.yaml” then passing the “current_values.yaml” to the sync/apply of helmfile.
The workaround requires adding an extra step before running helmfile and it produce an extra file, whilst it can be much more cleaner if it can be achieved using only helmfile.

**Comment by yxxhero** [comment]
https://github.com/helmfile/helmfile/blob/main/docs/proposals/towards-1.0.md
@Hamdiovish 
We have plan to slove this issue. Thanks very much.

**Comment by mumoshu** [comment]
@Hamdiovish Hey! Just curious, but why do you need to use `--reuse-values`?

In your example, what's the rationale behind reintaing the old kvs in the configmap that are rendered by the previous state of `values.yaml`?

I think your helmfile.yaml and a set of values.yaml should contain the all the information required to rebuild your the whole set of helm releases in your cluster, hence it's more "declarative". `--reuse-values` seems to reduce the declarativeness to me 🤔

**Comment by Hamdiovish** [comment]
Hi @mumoshu,
In the context of automation and CICD in microservice world, every component contains its CI pipeline, its deployment and CD logic including its helm chart.

These type of helm release could be updated from different positions: CI, CD, centralized config server. Also its values can depends on multiple source.

So, if we’re updating the helm release from a CI pipeline, it is enough to update the Docker TAG, without the need to accès the other dependencies to regenerate all the values.

This is just a simple use case which can be solved using the helm flag « —reuse-vaues » .

Also you may come to situations where you need to update values using CLI, without « —reuse-values » you’ll be obligated to pass all the values at every update, even if you want to update one single option, otherwise all the values will be reinitialized.

And much more situations!

**Comment by mumoshu** [comment]
@Hamdiovish Yeah, I do realize `--reuse-values` is useful when the whole helm values are present only on install and on upgrade you do have access to image tag only. But why is that with Helmfile? 🤔 I'm quite confused. Do you have a pair of helmfile.yaml, one for the first install and second for updates?? If so, why? If not, why do you need `reuse-vaues`?

**Comment by Hamdiovish** [comment]
@mumoshu do you mean why not to just use “helm apply —reuse-value” in this situation instead of “helmfile”?

Actually yes, I’m using two helmfile files.
The 1st type of helmfile files is living in every microservice within the CICD section, in this helmfile, I’m using the secret feature combined with SOPS, the feature of using env variable, the multi environment feature etc. This helmfile is invoked in every CD update.

The 2nd helmfile files type is living in another centralized project that listens to changes in the centralized config store, Consul KV. In this helmfile I’m using the Git repo feature, the secret feature, env variable and multi environment support.
This hellfile is referencing multiple micro services charts using git plugin via helmfile, and uses a dynamically generated values.yaml that contains only the updates values.
The problem started here, when I want to only apply the updated values using helmfile, the non-updated values that don’t exist in the new generated values.yaml, will be reset to the default values of the chart, a problem which can be solved using the logic of “—reuse-values” of helm and not available in Helmfile.

I found a workaround which is based on pulling the current values of the release using “helm get values -o yaml” then prepend the result to helmfile with “—values”, you can find more details regarding the workaround above.

Hopefully this answers your questions, otherwise feel free to ask for more clarification.

**Comment by mumoshu** [comment]
@Hamdiovish Hey! Thanks for clarifying. I think I'm almost close to understand your use-case.

> The 1st type of helmfile files is living in every microservice within the CICD section, in this helmfile, I’m using the secret feature combined with SOPS, the feature of using env variable, the multi environment feature etc. This helmfile is invoked in every CD update.

You'd need `--reuse-values` also for this first helmfile? Otherwise, every CD update would result in erasing changes made by the 2nd helmfile.

**Comment by Hamdiovish** [comment]
@mumoshu thank you for your prompt reply!
Yeah that’s exactly the case.
When I dry-run it, I found out that helmfile use **always** the default values with the provided values by the user, which I think it’s the real problem and may open the door for other incompatibility because it goes against Helm logic, since the default values in helm are located at the chart level and are rarely updated, so no need to provide it at every single upgrade or install, which is not the case for helmfile.
I think this is the source of the problem, improving this may align helmfile with the helm behavior and will allow the usage of the rest of helm features, —reuse-values and others, without the need to do any extra effort on the helmfile side.

**Comment by mumoshu** [comment]
Thanks again for your confirmation!

> it goes against Helm logic

Yep, helmfile enforces `--reset-values` (not `--reuse-values`) to make Helm more declaratively. Your use-case is very new to me!

**Comment by mumoshu** [comment]
> I think this is the source of the problem, improving this may align helmfile with the helm behavior and will allow the usage of the rest of helm features, —reuse-values and others, without the need to do any extra effort on the helmfile side.

If you meant helmfile should quit adding `--reset-values`, that's a no-go for us unfortunately.. It will break almost everyone using Helmfile over Helm to manage helm releases declaratively.

But adding an option like `helmfile --reset-values` to loosen Helmfile's declarative-ness for your specific use-case doesn't sound too bad to me.

**Comment by mumoshu** [comment]
@Hamdiovish Hey! Do you prefer to repurpose this issue for a feature request to add `--reset-values` to helmfile?

**Comment by Hamdiovish** [comment]
@mumoshu i think you mean to add "--reuse-values", since "--reset-values" is the current default behavior of Helmfile, isn't?
And yes of course, feel free to reformulate the issue for the suitable format.

**Comment by mumoshu** [comment]
@Hamdiovish Yep, I meant `reuse-values`! Thanks for pointing it out.

Are you going to use `helmfile --reset-values` if it's added?

**Comment by Hamdiovish** [comment]
As mentioned above, I’m pulling the current values using “helm get values” and storing it into a local file, then I append it to helmfile using “helmfile sync —values …” .
All of this could be avoided if “—reuse-values” would be available.
So yes, I would use “—reuse-values” if it will be added.
