### ISSUE TITLE
Broken output in powershell / windows

### ISSUE THREAD

**Issue by itscaro** [helmfile/helmfile#226]
### Operating system

Windows

### Helmfile Version

0.145.2

### Helm Version

3.9.0

### Bug description

<img width="565" alt="image" src="https://user-images.githubusercontent.com/266018/178699246-554e76c2-f885-4e7a-95cf-38cf7366ca70.png">

### Example helmfile.yaml

no need

### Error message you've seen (if any)

no

### Steps to reproduce

no need

**Comment by yxxhero** [comment]
@itscaro "\n" issue?

**Comment by itscaro** [comment]
@yxxhero I don't know, just updated to 0.145.2 and I saw this behavior.

**Comment by itscaro** [comment]
@yxxhero it's not helmfile but helm-secrets
