### ISSUE TITLE
Local kubernetes manifest folder fails with cryptic error message when .yml extension is used instead of .yaml

### ISSUE THREAD

**Issue by Weissger** [helmfile/helmfile#229]
### Operating system

macOS 12.3.1

### Helmfile Version

0.145.2

### Helm Version

v3.9.0

### Bug description

File extension `.yml` is not supported for local manifests.

### Example helmfile.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.8.1
  - name: cluster-issuer
    namespace: cert-manager
    chart: ./manifests # See here. This fails if .yml is placed into the directory instead of .yaml

### Error message you've seen (if any)

n ./helmfile.yaml: [assertion failed: unexpected dir entry : it mnust be a abs path]

### Steps to reproduce

https://github.com/Weissger/helmfile-yaml-yml

**Comment by yxxhero** [comment]
@Weissger I will work on this.

**Comment by yxxhero** [comment]
does this commit https://github.com/variantdev/chartify/commit/acafe90d99962ac9e2464ffc88db2200129a9631 fix the issue? @mumoshu

**Comment by mumoshu** [comment]
@yxxhero That commit does fix the cryptic error message, but not the underlying issue that it can't process `.yml` files. I don't think `.yml` files are well supported on k8s-related toolings like helm or kubectl and perhaps it worth being supported in chartify? 🤔

**Comment by yxxhero** [comment]
@mumoshu  yes. I think so. I think it should add in chartify.

**Comment by mumoshu** [comment]
https://github.com/variantdev/chartify/pull/39 seems to work by adding the ability to detect the directory as a k8s manifests even when the files contained in the directory were not .yaml files but .yml files.

**Comment by mumoshu** [comment]
https://github.com/variantdev/chartify/releases/tag/v0.11.0 includes the fix for this issue.
