### ISSUE TITLE
Need help with helm upgrade&kubectl apply

### ISSUE THREAD

**Issue by ljie-16** [helmfile/helmfile#232]
### Operating system

ubuntu 20.02.4

### Helmfile Version

v3.3.4+5.el8

### Helm Version

v3.3.4+5.el8

### Bug description

The helm upgrade command i use: helm upgrade vdu "nodename/charts/podname/templates/values.yaml" --set xx.yyy=2
Error: Error: failed to download "nodename/charts/podname/templates/values.yaml" (hint: running `helm repo update` may help)

Another issue with kubectl apply -f
Command: kubectl apply -f configmap.yaml
error: error: error parsing configmap.yaml: error converting YAML to JSON: yaml: line 3: did not find expected key

### Example helmfile.yaml

NA

### Error message you've seen (if any)

NA

### Steps to reproduce

No

**Comment by yxxhero** [comment]
@ljie-16 Please create issue in https://github.com/helm/helm
