### ISSUE TITLE
Namespace override ignored when resolving temporary (including OCI fetched charts)

### ISSUE THREAD

**Issue by jgchristian** [helmfile/helmfile#242]
### Operating system

MacOS

### Helmfile Version

v0.145.2

### Helm Version

v3.9.0

### Bug description

Steps to reproduce
---
- Define an OCI repository in your helmfile
- Define a release that includes a valid reference to an OCI managed chart; but do not specify a namespace in the release defintion
- Run `helmfile --namespace my-namespace sync` or `helmfile --namespace my-namespace template` 

Expected behaviour
---
- OCI chart is resolved and sync'd/templated

Actual
---
- Error thrown by helm `Error: failed to download "my-oci-repo/my-chart" at version "1.0.2"`

Some analysis
---
This error **does not** occur if 
  - you do not specify `--namespace my-namespace` arg to `helmfile`, or
  - you specify `releases[x].namespace` in your helmfile

In the working state, we see the call to helm includes a reference to the temporary folder containing the OCI downloaded chart.  In the broken state we see the chart reference as is (i.e. `my-oci-repo/my-chart`)

Looking at the code, it seems that namespace and kube context overrides are not being considered when looking up the local/temporarily downloaded.

Workaround
---
Specify a `namespace: {{ .Namespace }}` attribute in the release definitions in `helmfile.yaml`

I will attach a sample PR that highlights the problematic lookup.

### Example helmfile.yaml

```
# helmfile.yaml
repositories:
  - name: my-oci-repo
    url: my-ocirepo.com/charts
    oci: true

releases:
  - name: my-release
    chart: my-oci-repo/my-chart
    version: 1.0.2
    # Note "namespace" not included here.  If we were to add "namespace: {{ .Namespace }}" this works fine.

```

Run with `helmfile --namespace my-namespace template`

### Error message you've seen (if any)

OCI downloader successfully doing it's thing...

```
Pulling my-oci-repo/charts/my-chart:1.0.2
Exporting my-oci-repo/charts/my-chart:1.0.2
Pulled: my-oci-repo/charts/my-chart:1.0.2
Digest: sha256:d6cfc9e3f18eb18191132c68515dcc490945a6f19b0b83d12c13a377103e043b

Exporting my-oci-repo/charts/my-chart:1.0.2
Pulled: my-oci-repo/charts/my-chart:1.0.2
```

-- SNIP ---

Helm barfing...

```
ARGS:
  0: helm (4 bytes)
  1: template (8 bytes)
  2: my-release (14 bytes)
  3: my-oci-repo/my-chart (26 bytes)
  4: --version (9 bytes)
  5: 1.0.2 (13 bytes)
  6: --namespace (11 bytes)
  7: my-namespace (20 bytes)
  8: --values (8 bytes)
  9: /var/folders/wd/nf72qyt51c99_kyl2lb7vcsc0000gp/T/helmfile338136752/my-namespace-my-release-values-7468884646 (120 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: failed to download "my-oci-repo/my-chart" at version "1.0.2"
```

### Steps to reproduce

See above

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@jgchristian Thanks very much. I will check this.

**Comment by yxxhero** [comment]
@xiaomudk do you have free time to see this issue? Thanks very much.

**Comment by xiaomudk** [comment]
@yxxhero ok, let me follow up

**Comment by yxxhero** [comment]
@jgchristian Thanks very much. Thanks for works for this issue.

**Comment by xiaomudk** [comment]
@jgchristian This error doesn't look like a namespace issue.
Can you use `--debug` and let me see the output, for example:
```
helmfile --namespace my-namespace2 sync --debug
```
find this one
```
processing releases in group 1/1: my-namespace/nginx
Upgrading release=nginx, chart=nginx-stable/nginx-ingress
exec: helm upgrade --install --reset-values nginx nginx-stable/nginx-ingress --version 0.14.0 --create-namespace --namespace my-namespace  --history-max 10
```

**Comment by xiaomudk** [comment]
It has something to do with helm oci, let me see it again

**Comment by xiaomudk** [comment]
@jgchristian  I use oci test and it can be used normally, but in oci mode, there may be problems with the parsing of helm url and version.  See here for details #244. If you don't have a similar problem, please use `--debug` to let me see the detailed execution process. Thanks!

**Comment by jgchristian** [comment]
Hi

I just spent a couple of hours trying to create a simple test harness with the latest versions of helm, helmfile and harbor... plus a much simpler `helmfile.yaml` and failed to reproduce the issue... so I'm wondering if there is an exotic issue triggered by our specific pipeline and production helmfile configuration.  

I'll close this issue for now and monitor in our pipelines.

Thanks for taking a look... apologies if any time was wasted!
