### ISSUE TITLE
lint: Error: flag provided but not defined: -include-needs

### ISSUE THREAD

**Issue by Morriz** [helmfile/helmfile#247]
### Operating system

Ubuntu:20.04

### Helmfile Version

0.145.0

### Helm Version

3.9.0

### Bug description

When providing selector that has `needs:` an error is thrown:
```
Error: flag provided but not defined: -include-needs
```

Is this not consistently added to all contexts that need it? `template`, `diff` and `apply` work ok with it.

### Example helmfile.yaml

releases:
  - name: gatekeeper-artifacts
    installed: true
    needs: [gatekeeper]

### Error message you've seen (if any)

```
   helmfile lint - lint charts from state file (helm lint)

USAGE:
   helmfile lint [command options] [arguments...]

OPTIONS:
   --args value         pass args to helm exec
   --set value          additional values to be merged into the command
   --values value       additional value files to be merged into the command
   --concurrency value  maximum number of concurrent downloads of release charts (default: 0)
   --skip-deps          skip running "helm repo update" and "helm dependency build"
2022-07-21T10:04:38.118Z otomi:cmd:lint:lint:error flag provided but not defined: -include-needs
2022-07-21T10:04:38.127Z otomi:global:error Error: flag provided but not defined: -include-needs
```

### Steps to reproduce

lint a release with needs

### Working Helmfile Version

0

**Comment by mumoshu** [comment]
Internally it's implemented and tested in the code added via https://github.com/helmfile/helmfile/pull/78, but apparently I didn't add the definitions for corresponding command-line flags in the same pull request.

@yxxhero Would you mind adding the flags to the corresponding pflags/cobra command? Thanks!

**Comment by yxxhero** [comment]
@mumoshu yes. I will do this in this week.

**Comment by yxxhero** [comment]
@mumoshu added. Thanks very much.
