### ISSUE TITLE
helmfile --environment cli arg regression

### ISSUE THREAD

**Issue by jouve** [helmfile/helmfile#249]
### Operating system

os x

### Helmfile Version

canary

### Helm Version

n/a

### Bug description

before cobra migration:
   --environment value, -e value           specify the environment name. defaults to "default"

after cobra migration (#234):
  -e, --env string                      specify the environment name. defaults to "default"

the environment long option changed from --environment to --env

### Example helmfile.yaml

n/a

### Error message you've seen (if any)

Error: unknown flag: --environment

### Steps to reproduce

`helm --environment myenv template` 

### Working Helmfile Version

v0.145.0

**Comment by yxxhero** [comment]
https://github.com/helmfile/helmfile/pull/250
