### ISSUE TITLE
helmfile --help cli regression

### ISSUE THREAD

**Issue by jouve** [helmfile/helmfile#251]
### Operating system

ubuntu

### Helmfile Version

canary

### Helm Version

n/a

### Bug description

helmfile --help produce a warning instead of the help: 
``` 
helmfile --help
WARNING: pflag: help requested
``` 

it looks like the  issue decribed in https://github.com/kubernetes/minikube/pull/9614 

### Example helmfile.yaml

n/a

### Error message you've seen (if any)

` WARNING: pflag: help requested`

### Steps to reproduce

` helmfile --help` 

### Working Helmfile Version

v0.144.0

**Comment by yxxhero** [comment]
https://github.com/helmfile/helmfile/pull/252
