### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by mugioka** [helmfile/helmfile#267]
### Operating system

Linux

### Helmfile Version

none

### Helm Version

none

### Bug description

cannot install helmfile with correct arch.

### Example helmfile.yaml

none

### Error message you've seen (if any)

```
bash: ./helmfile: cannot execute binary file: Exec format error
```

### Steps to reproduce

```bash
root@test:/# HELMFILE_VERSION=0.145.0
root@test:/# uname   
Linux
root@test:/# arch
x86_64
root@test:/# wget -qO /helmfile https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz;
root@test:/# chmod 755 ./helmfile 
root@test:/# ./helmfile 
bash: ./helmfile: cannot execute binary file: Exec format error
root@test:/# rm ./helmfile 
root@test:/# wget -qO /helmfile https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_386.tar.gz;
root@test:/# chmod 755 ./helmfile 
root@test:/# ./helmfile
bash: ./helmfile: cannot execute binary file: Exec format error
```

I am trying with HELMFILE_VERSION 0.145.0, but 0.145.* all don't seem to install the correct binaries.

### Working Helmfile Version

none

**Comment by yxxhero** [comment]
@mugioka I can't reproduce your issue. Thanks very much. 
 https://github.com/helmfile/helmfile/releases/download/v0.145.2/helmfile_0.145.2_linux_amd64.tar.gz

**Comment by pathob** [comment]
@mugioka How about extracting the `.tar.gz`? ;-)

**Comment by yxxhero** [comment]
> @mugioka How about extracting the `.tar.gz`? ;-)
> 
> Edit: To be fair: I also stumbled over the fact the artifacts are compressed now.

yes. It should be uncompressed. @mugioka

**Comment by mugioka** [comment]
Oh, sorry. I forget to uncompressed.
Thank you 🙏
