### ISSUE TITLE
helmfile --version flag missing in the Docker image

### ISSUE THREAD

**Issue by peikk0** [helmfile/helmfile#289]
### Operating system

OSX 12.5

### Helmfile Version

v0.145.2

### Helm Version

v3.9.3

### Bug description

When using the Docker image `ghcr.io/helmfile/helmfile:v0.145.2` the flag `--version` doesn't exist and `helmfile version` doesn't return the version either:
```
❯ docker run ghcr.io/helmfile/helmfile:v0.145.2 helmfile --version
Incorrect Usage. flag provided but not defined: -version

NAME:
   helmfile

USAGE:
   helmfile [global options] command [command options] [arguments...]

...
```

```
❯ docker run ghcr.io/helmfile/helmfile:v0.145.2 helmfile version
helmfile version
```

Locally the same version works fine:
```
❯ helmfile --version
helmfile version v0.145.2
```

```
❯ helmfile version
helmfile version v0.145.2
```

### Example helmfile.yaml

n/a

### Error message you've seen (if any)

```
❯ docker run ghcr.io/helmfile/helmfile:v0.145.2 helmfile --version
Incorrect Usage. flag provided but not defined: -version
```

### Steps to reproduce

```sh
docker run ghcr.io/helmfile/helmfile:v0.145.2 helmfile --version
```

```sh
docker run ghcr.io/helmfile/helmfile:v0.145.2 helmfile version
```

### Working Helmfile Version

n/a

**Comment by yxxhero** [comment]
@peikk0 Thanks for your issue. fixed in https://github.com/helmfile/helmfile/pull/294
