### ISSUE TITLE
Passing `--args "--show-only path/to/template.yaml"` works but not `--args "-s path/to/template.yaml"`

### ISSUE THREAD

**Issue by bderrly** [helmfile/helmfile#299]
### Operating system

Ubuntu 20.04

### Helmfile Version

0.145.3

### Helm Version

3.8.1

### Bug description

I want to only render a single template file by using the `-s|--show-only` flag on `helm template`. I see that I can pass arbitrary flags to `helm template` by using `helmfile template --args`. However, running `helmfile template --args` and passing the `-s` flags does not work but the full flag name `--show-only` does.

Example failing command: `helmfile -e dev -l name=foo --skip-needs --skip-deps template --args "-s templates/deployment.yaml"`

### Example helmfile.yaml

```yaml
releases:
- name: foo
  namespace: foo
  chart: charts/foo
```

### Error message you've seen (if any)

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/helmfile/helmfile/pkg/config.NewCLIConfigImpl(0xc000410310)
        /home/runner/work/helmfile/helmfile/pkg/config/config.go:18 +0x432
github.com/helmfile/helmfile/cmd.NewTemplateCmd.func1(0xc000819b80?, {0x17178cf?, 0x8?, 0xc?})
        /home/runner/work/helmfile/helmfile/cmd/template.go:19 +0x29
github.com/spf13/cobra.(*Command).execute(0xc000819b80, {0xc000308780, 0x8, 0xc})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc00088ca00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/runner/work/helmfile/helmfile/main.go:25 +0xbc

### Steps to reproduce

N/A

### Working Helmfile Version

unknown

**Comment by yxxhero** [comment]
@bderrly try to use `-s=templates/deployment.yaml`

**Comment by mumoshu** [comment]
`--args` turned out to be a fundamentally bad idea and you should use it only as a last resort and you can't still expect it to work as you might have expected... We don't know how to correctly and automatically map which `args` are passed to which helm sub-command(s) being involved in a single helmfile execution.

**Comment by mumoshu** [comment]
But hey, shouldn't we just implement `-s|--show-only` for helmfile-template? It should be usable only with `-l 
 --selector` though.
