### ISSUE TITLE
helmfile not working with helm3 of microk8s

### ISSUE THREAD

**Issue by skliarie** [helmfile/helmfile#313]
### Operating system

Ubuntu 22.04 LTS

### Helmfile Version

0.145.3

### Helm Version

v3.8.0

### Bug description

Installed microk8s (as snap), enabled helm3.
When running helmfile, it can not find helm binary (in microk8s it is supposed to be run using "microk8s helm3").
If specifying binary explicitly, other error pops up:
```
helmfile apply -b /snap/bin/microk8s.helm3 --file helmfile.yaml
...
Error: unknown command "diff" for "helm"
```

### Example helmfile.yaml

repositories:
 - name: bitnami
   url: https://charts.bitnami.com/bitnami

releases:
- name: redis-padm
  namespace: k8dev
  chart: bitnami/redis
  set:
  - name: primary.persistence.size
    value: 20Gi
  - name: auth.password
    value: "some_pwd462"
  - name: master.persistence.enabled
    value: true
  - name: master.persistence.storageClass
    value: "rook-ceph-block"

### Error message you've seen (if any)

Error: unknown command "diff" for "helm"

### Steps to reproduce

helmfile apply -b /snap/bin/microk8s.helm3 --file helmfile.yaml 

### Working Helmfile Version

0.145.3

**Comment by yxxhero** [comment]
@skliarie please install helm-diif plugin. Thanks very much.

**Comment by yxxhero** [comment]
@skliarie Please see https://github.com/databus23/helm-diff

**Comment by skliarie** [comment]
Installed, now helmfile works, thank you very much!
