### ISSUE TITLE
Wrong git tag v0145.4 (without first dot)

### ISSUE THREAD

**Issue by evgkrsk** [helmfile/helmfile#316]
### Operating system

-

### Helmfile Version

-

### Helm Version

-

### Bug description

Release 0.145.4 artifacts have wrong names without first dot in version string: "helmfile_01454_checksums.txt" and so on.

Probably root cause is wrongly named git tag: v0145.4 (previous tag was v0.145.3).

### Example helmfile.yaml

-

### Error message you've seen (if any)

-

### Steps to reproduce

-

### Working Helmfile Version

0.145.3

**Comment by yxxhero** [comment]
@evgkrsk Thanks very much. @mumoshu ping

**Comment by yxxhero** [comment]
done @mumoshu @evgkrsk Thanks very much.

**Comment by evgkrsk** [comment]
Please rebuild binaries in homebrew tap:
```
[unable to resolve 11 deps: the lockfile was created by Helmfile v0145.4, which is newer than current 0.145.4; Please upgrade to Helmfile v0145.4 or greater]
```

**Comment by evgkrsk** [comment]
@mumoshu @yxxhero

**Comment by yxxhero** [comment]
https://github.com/helmfile/helmfile/releases/download/v0.145.4/helmfile_0.145.4_darwin_arm64.tar.gz is ok.

**Comment by mumoshu** [comment]
@evgkrsk Thanks for the notice! Unforunately, we don't maintain the tap so.. maybe you need to contact the maintainer of it?

**Comment by mumoshu** [comment]
@evgkrsk Also, I guess it might go through if you uninstalled and reinstalled the helmfile tap. Have you already tried that?

**Comment by yxxhero** [comment]
@mumoshu @evgkrsk I will create a isssue in https://github.com/Homebrew/homebrew-core

**Comment by yxxhero** [comment]
https://github.com/Homebrew/homebrew-core/pull/108948
