### ISSUE TITLE
`helmfile sync --interactive` does not ask for confirmation before applying

### ISSUE THREAD

**Issue by WoodyWoodsta** [helmfile/helmfile#324]
### Operating system

macOS 12.15.1

### Helmfile Version

v0145.4

### Helm Version

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

### Bug description

When I run `sync` with the `--interactive` flag, I do not get a confirmation before helmfile makes changes to my cluster.

### Example helmfile.yaml

N/A

### Error message you've seen (if any)

N/A

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@WoodyWoodsta PR is welcome.

**Comment by yxxhero** [comment]
@WoodyWoodsta From the code. In sync subcommand, no logic for interactive.

**Comment by yxxhero** [comment]
@WoodyWoodsta I will try to add it in sync. wait my PR or your PR. haha

**Comment by WoodyWoodsta** [comment]
Thanks @yxxhero - if I get some time I can have a quick look but I work full-time, so we'll see 😄

**Comment by yxxhero** [comment]
@WoodyWoodsta OpenSource requires all of us.

**Comment by mumoshu** [comment]
Hey! Thanks for reporting and investigating.
Probably this was an unintended regression introduced when we migrated our CLI framework from urfave/cli to cobra?
Just to be clear, the point of `--interactive` was to let Helmfile ask AFTER showing the diff and BEFORE actually applying the changes.
So, from the author's perspective, I can say it's working as intended.
Please use `helmfile apply` if you need interactivity!

**Comment by mumoshu** [comment]
And we might be adding support for `sync` and `delete` as well via #328

**Comment by WoodyWoodsta** [comment]
@mumoshu Thanks - explained that way I now understand that `apply` is a "superset" command including `diff` and `sync`, and that `--interactive` is to ask for confirmation before those two steps. Coming from `kubectl apply` and `helm upgrade`, I assumed `sync` to be more of the latter (which does a diff internally).
