### ISSUE TITLE
`--state-values-set` is always a string

### ISSUE THREAD

**Issue by philomory** [helmfile/helmfile#334]
### Operating system

Windows 10

### Helmfile Version

0.145.4

### Helm Version

3.9.3

### Bug description

Given a `helmfile.yaml` containing the following snippet:
```
{{- if ge .Values.example 2 }}
foo: bar
{{- end }}
```
When executing the command e.g. `helmfile --state-values-set example=3`, instead of evaluating the contents of the conditional block, you will get the error, `executing stringTemplate at <lt .Values.example 2>: error calling lt: incompatible types for comparison`. This is because, unlike with Helm's `--set` flag, Helmfile's `--state-values-set` flag treats all values as strings.

### Example helmfile.yaml
```
values:
  - foo: 1

repositories:
  - name: jenkins-x
    url: https://jenkins-x-charts.github.io/v2/

releases:
  - name: empty
    chart: jenkins-x/empty
    version: 0.0.3
    values:
      {{- if ge .Values.foo 2 }}
      - configMap:
          enabled: true
      {{- else }}
      - configMap:
          enabled: false
      {{- end }}
```

### Error message you've seen (if any)
```
$ helmfile --state-values-set foo=3 apply
Error: in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:13:13: executing "stringTemplate" at <ge .Values.foo 2>: error calling ge: incompatible types for comparison
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:13:13: executing "stringTemplate" at <ge .Values.foo 2>: error calling ge: incompatible types for comparison
```
### Steps to reproduce

https://github.com/philomory/helmfile-bug-str

### Working Helmfile Version

None, that I am aware of

**Comment by yxxhero** [comment]
http://masterminds.github.io/sprig/conversion.html  I thinks this can help you.

**Comment by philomory** [comment]
Template function such as `atoi` provide a passable workaround, but they shouldn't be considered an actual _solution_ to this problem. In the old repository there was [an issue for this as well](https://github.com/roboll/helmfile/issues/1347), in the context of booleans - and for booleans the situation is even worse, since there does not exist any sprig function to turn `"true"` and `"false"` into `true` and `false`, leaving you stuck writing code like `{{- if (eq (toString .Values.example) "true") }}` at _every_ place where you might otherwise simply write `{{- if .Values.example }}`.

In fact, for Booleans it gets even worse than that, because as noted in the original ticket from the old repository, the "condition" field on a release _must_ refer to a boolean values key, by name. The only workaround there would be something like `condition: {{ eq (toString .Values.foo.enabled) "true" | ternary "alwaysTrue.enabled" "alwaysFalse.enabled" }}` with keys `alwaysTrue.enabled` and `alwaysFalse.enabled` set to `true` and `false` respectively.

**Comment by yxxhero** [comment]
@philomory PR is welcome. Thanks very much.
