### ISSUE TITLE
Unable to alias "--interactive" flag anymore

### ISSUE THREAD

**Issue by nervo** [helmfile/helmfile#366]
### Operating system

Irrelevant

### Helmfile Version

0.145.5

### Helm Version

Irrelevant

### Bug description

Now that "interactive" flag has been removed from global options (https://github.com/helmfile/helmfile/pull/328) we could no longer use it in a shell alias, like described here https://github.com/helmfile/helmfile/blob/main/docs/index.md#running-helmfile-interactively

Indeed, the interactive flag is now supposed to be put *after* the command:
```
$ helmfile --interactive apply
unknown flag: --interactive

$ helmfile apply --interactive
Adding repo........ (ok)
```

Please, consider make the flag global again, or, perhaps introduce the usage of a dedicated environment variable, like
```
alias hi='HELMFILE_INTERACTIVE=1 helmfile'
```

And btw, thanks for your great application, and your hard work :)

### Example helmfile.yaml

Irrelevant

### Error message you've seen (if any)

Irrelevant

### Steps to reproduce

Irrelevant

### Working Helmfile Version

Irrelevant

**Comment by yxxhero** [comment]
@nervo good catch. @mumoshu WDYT? if need make the --interactive global again, I will do. Or, perhaps introduce the usage of a dedicated environment variable.

**Comment by yxxhero** [comment]
`--interactive` only takes effect in a subset of subcommands.

**Comment by nervo** [comment]
@yxxhero yes, but we have always consider it as a "switch" to let the entire application work in interactive mode in critical situations :)
I know cobra (https://github.com/spf13/cobra) could be associated with viper (https://github.com/spf13/viper) to handle options as config files or environment variables, maybe that could be a solution :)

**Comment by yxxhero** [comment]
@nervo PR is welcome. Thanks very much.

**Comment by nervo** [comment]
@yxxhero  it would be a pleasure, but i have to know where to going to :) Rollback to global ? environment variable ? viper ? something else ?

**Comment by yxxhero** [comment]
@mumoshu WDYT? thanks very much.

**Comment by mumoshu** [comment]
@nervo @yxxhero Hey! Thanks a lot for raising this. I believe we should roll it back to a global flag, as we intentionally made it so 4 years ago and the rationale behind the decision still stands today https://github.com/roboll/helmfile/issues/354#issuecomment-424028564

**Comment by yxxhero** [comment]
@nervo ok. So do you have free to do this? Thanks very much.

**Comment by nervo** [comment]
Wooo @yxxhero you're too fast for me :)
