### ISSUE TITLE
Error: unknown command "view" for "helm" when using helm-secrets

### ISSUE THREAD

**Issue by kevin1sMe** [helmfile/helmfile#404]
### Operating system

Ubuntu 20.04.4 LTS

### Helmfile Version

Helmfile version 0.145.5

### Helm Version

version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}

### Bug description

When I using helm-secrets, do something like:
```bash
helmfile diff
```

I think this error cause  because of [helm-secrets](https://github.com/jkroepke/helm-secrets/blob/v4.1.1/CHANGELOG.md#400---2022-09-11) change the command:

>Remove `helm secret view` command. The helm secret decrypt command is a drop-in replacement.

I had downgrade helm-secrets to `3.15.0`,  it work fine.

### Example helmfile.yaml

environments:
  default:
    values:
    - env.yaml
    secrets:
    - prod/secrets-helm-enc.yaml
releases:
- name: ddns
  namespace: ddns
  chart: ./../../charts/ddns
  values:
    - values.yaml
    - DNSPod: 
        ID: {{ .Values.DNSPodID }}
        Token: {{ .Values.DNSPod.Token| quote }}

### Error message you've seen (if any)

ARGS:
  0: helm (4 bytes)
  1: secrets (7 bytes)
  2: view (4 bytes)
  3: /root/xxx/prod/secrets-helm-enc.yaml (68 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: unknown command "view" for "helm"
  Run 'helm --help' for usage.
  Error: plugin "secrets" exited with error

### Steps to reproduce

null

### Working Helmfile Version

Helmfile version 0.145.5

**Comment by yxxhero** [comment]
@kevin1sMe Please use 0.146.0. It supports helm-secret v4.x

**Comment by yxxhero** [comment]
@kevin1sMe If v0.146.0 solve your issue. Please close this issue. Thanks very much.

**Comment by yxxhero** [comment]
if your company uses helmfile. Can you create a PR for https://helmfile.readthedocs.io/en/latest/users/. Thanks very much.

**Comment by kevin1sMe** [comment]
> @kevin1sMe Please use 0.146.0. It supports helm-secret v4.x

Thanks， solved。
