### ISSUE TITLE
Embedded helmfiles accessing through ssh not working, when using helmfile dockerimage

### ISSUE THREAD

**Issue by stunsara** [helmfile/helmfile#41]
### Operating system

Mac OS 12.0.1

### Helmfile Version

0.144.0

### Helm Version

v3.7.2

### Bug description

SSH bin is absent in helmfile dockerimage.

**Images affected:**
quay.io/roboll/helmfile:v0.144.0-stable-slim
quay.io/roboll/helmfile:v0.144.0

### Steps to reproduce

1. Helmfile.yaml:
```
helmfiles:
- path: git::ssh://git@server.org/repo.git@helm/helmfile.yaml?ref=master

...
```
2. Try to sync/template/test with cmd:
```
docker run --rm --net=host -v "${KUBECONFIG}:/root/.kube/config" -v "${PWD}:/wd" --workdir /wd quay.io/roboll/helmfile:v0.144.0 helmfile template
```

**Actual result:**
```
in ./helmfile.yaml: in .helmfiles[0]: locate: get: error downloading 'ssh://git@server.org/repo.git@helm/helmfile.yaml?ref=master': /usr/bin/git exited with 128: Cloning into '/root/.cache/helmfile/ssh_server_org_repo_git.ref=master'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

**Comment by mumoshu** [comment]
What do you mean by "No response" in the `Relevant discussion` field? 🤔 I couldn't locate any related discussions in the Discussions page.

**Comment by mumoshu** [comment]
Hey. Is this really a bug?
I thought we had never discussed what to be included in our official container image.
Is including everything to support every use-case is a good thing for the project? 🤔

**Comment by stunsara** [comment]
> What do you mean by "No response" in the `Relevant discussion` field? 🤔 I couldn't locate any related discussions in the Discussions page.

As i have understood - it's default value for this field, in issue wizard, didn't touch it at all :)

> Hey. Is this really a bug? I thought we had never discussed what to be included in our official container image. Is including everything to support every use-case is a good thing for the project? 🤔

From the user's point of view - definitely yes. Using offical image, i expect all features to work properly. 
Plus, I was searching mistakes in my helmfile.yaml, when hitted this problem.

**Comment by mumoshu** [comment]
> As i have understood - it's default value for this field, in issue wizard, didn't touch it at all :)

@stunsara Ah, really! Thanks for clarifying. I never realized that it behaves like that because I didn't put the default value in the issue form declaration at all!

> From the user's point of view - definitely yes. Using offical image, i expect all features to work properly.
Plus, I was searching mistakes in my helmfile.yaml, when hitted this problem.

That makes sense! We need to do our best to not surprise users using the official image.

Would you mind contributing an enhancement to our dockerfile?
