### ISSUE TITLE
function fetchSecretValue fails if cannot find secret

### ISSUE THREAD

**Issue by poligraph** [helmfile/helmfile#431]
### Operating system

MacOS

### Helmfile Version

v0.145.3

### Helm Version

v3.10.0

### Bug description

Previously I store secrets in sops encrypted file and used `get` function for accessing this secrets.
I have quite a lot of environments and it's not always all secrets exist in every env.

`get` function could have default value as described here:
https://github.com/helmfile/helmfile/blob/main/docs/writing-helmfile.md
https://github.com/roboll/helmfile/pull/1268/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R535

so this configuration works perfectly when no `auth_token` exist in env and set auth_token to `""` (empty default value)

```
auth_token: "{{ .Values | get "auth_token" "" }}"
```

but after migration I cannot use `fetchSecretValue` with same behaviour

this code will fail if no `auth_token` in google secret manager or no versions - function fails
```
auth_token: "{{ .Values | fetchSecretValue "auth_token" }}"
```

this code will fail because `fetchSecretValue` function cannot set default value if cannot fetch secret
```
auth_token: "{{ .Values | fetchSecretValue "auth_token" "" }}"
```

So it would be nice to fix these 2 issue with `fetchSecretValue` value

### Example helmfile.yaml

above

### Error message you've seen (if any)

err 34: failed processing release xxx: failed to render values files "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:1773:16: executing "stringTemplate" at <fetchSecretValue>: wrong number of args for fetchSecretValue: want 1 got 2

err 34: failed processing release xxx: failed to render values files "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:114:42: executing "stringTemplate" at <.Values.auth_token>: map has no entry for key "auth_token"

### Steps to reproduce

adove

### Working Helmfile Version

none

**Comment by poligraph** [comment]
related issue and discussions:
https://github.com/roboll/helmfile/issues/1728
https://github.com/variantdev/vals/issues/52
https://github.com/helmfile/helmfile/discussions/111
https://github.com/roboll/helmfile/issues/465
https://github.com/roboll/helmfile/pull/1268/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R535

**Comment by yxxhero** [comment]
@poligraph could you try to use `default`? Thanks very much.

**Comment by yxxhero** [comment]
@poligraph  @mumoshu 
add new func fetchSecretValueWithDefault?

**Comment by mumoshu** [comment]
@yxxhero I think you can't chain it with `default` because it returns an error when the secret is not found. And we have a similar function that works on `.Values` that is named `get`, which takes the default value as the second parameter. Maybe just add the optional second parameter as similar as the `get` function so that they are consistent?

**Comment by yxxhero** [comment]
@mumoshu yes. good idea.

**Comment by yxxhero** [comment]
@mumoshu @poligraph 
Let me ask a few questions. Errors will occur under the following conditions. Under what conditions is it safe for us to return the default value
1. Network error
2. Authority issues
3. Secret does not exist

**Comment by poligraph** [comment]
@mumoshu I think behaviour of `fetchSecretValue` should be the same as `get`

@yxxhero not sure about all three cases, but it should return default value if secret or secret version does not exist.

**Comment by yxxhero** [comment]
@poligraph The key question is how to know the secret or secret versions do not exist.

**Comment by poligraph** [comment]
@yxxhero if there is no secret reference in config file error is 
```
err 34: failed processing release xxx: failed to render values files "values.yaml.gotmpl": failed to render [values.yaml.gotmpl], because of template: stringTemplate:114:38: executing "stringTemplate" at <.Values.token>: map has no entry for key "token"
```

if reference exists in config file, but no in secret manager error is 
```
err 34: failed processing release xxx: failed to render values files "values.yaml.gotmpl": expand gcpsecrets://xxx/token: failed to get secret: rpc error: code = NotFound desc = Secret [token] not found or has no versions.

```

**Comment by yxxhero** [comment]
@poligraph ok. Thanks for your tips.

**Comment by vavdoshka** [comment]
Is there a way to run `template` with some sort of `dry-run` which would ignore the secrets fetch completely?
Putting some static placeholder instead of `ref+` references would also work.

The goal is to be able to `template` the manifests in environments where there is no access to secret backends.

**Comment by mumoshu** [comment]
> The goal is to be able to template the manifests in environments where there is no access to secret backends.

What's the point of doing this? If you don't have access to the secrets backend, shouldn't it just fail so that you can see why it doesn't work, rather than silently behaving as if it works?

**Comment by vavdoshka** [comment]
So our devs are developing their Helmfiles locally, within the envs with no access to secret backend,
Then the Helmfile is executed in ArgoCD with all the access so it actually renders correct manifest. (Instead of ArgoCD I can imagine it could be something like GitLab CI for example).

The goal is to simplify and shorten the feedback loop when developing Helmfile.
Local mock of secrets backend is something which solves the problem but it is quite heavy.

**Comment by vavdoshka** [comment]
indeed, nice approach @mumoshu

**Comment by pathob** [comment]
There is even an easier way, I'm also doing that with the `echo` and the Azure KeyVault backends:

```
environments:
  local:
    values:
      - vault: ref+echo:/  ## it is important to just have one '/' here!
  dev:
    values:
      - vault: ref+azurekeyvault://my-keyvault.vault.azure.net  ## may not have trailing '/'!

releases:
- name: myapp
  chart: mychart
  values:
  - foo: {{ .Values.vault }}/my-secret ## note: azure keyvault has no hierarchies
```

:)

**Comment by poligraph** [comment]
Hi @mumoshu I am just wondering if it any chance to see fix in the nearest future?

Thanks.

**Comment by poligraph** [comment]
@yxxhero @mumoshu Hello guys, is at any progress on that issue?

**Comment by yxxhero** [comment]
@poligraph I haven't started yet. if you have free time. Please free to post a PR for this feature.

**Comment by mumoshu** [comment]
I think the renaming or even the functionality of this feature might need careful consideration.

`get` applies the default value only when the value is not found in the given map.
On the contrary, `fetchSecretValueOrDefault` should return the default value only when the given key is empty, not when the said secret is inexistent. At least that seems to be the behavior desired by the OP.

In addition, how can we make the two fetchSecretValue variants when we ended up needing the one that applies the default value when the secret is inexistent too? `fetchSecretValueWithDefaultOnEmptyKey` for the former and `fetchSecretvalueWithDefaultOnMissingSecret`?!

**Comment by yxxhero** [comment]
@mumoshu make sense.
