### ISSUE TITLE
--debug is not set in helm template

### ISSUE THREAD

**Issue by itscaro** [helmfile/helmfile#463]
### Operating system

Windows

### Helmfile Version

0.147.0

### Helm Version

3.10.1

### Bug description

--debug is not transferred to helm template

### Example helmfile.yaml

try basic one

### Error message you've seen (if any)

debug command does not show `helm template --debug`

### Steps to reproduce

no need

### Working Helmfile Version

0.147.0

**Comment by itscaro** [comment]
@yxxhero Could you have a quick check on this one, I did not investigate, I encounter this when updating from <0.145 to 0.147

**Comment by yxxhero** [comment]
OK.

**Comment by yxxhero** [comment]
@itscaro good catch. I will fix it.

**Comment by yxxhero** [comment]
@itscaro please see: https://github.com/helmfile/helmfile/pull/465
