### ISSUE TITLE
Issue with windows separator

### ISSUE THREAD

**Issue by itscaro** [helmfile/helmfile#468]
### Operating system

Windows 11/10

### Helmfile Version

0.147.0

### Helm Version

3.10.1

### Bug description

`Upgrading release=xxx, chart=repo\chart`

Note "\" in the output.

This bug break helmfile with cygwin/bash.

In powershell + busybox, "\" does not break helm/helmfile, but it's still not nice to see "\"

helmfile template works but not helmfile sync, if it helps to investigate 

### Example helmfile.yaml

N/A

### Error message you've seen (if any)

![image](https://user-images.githubusercontent.com/266018/197751544-09dc75a2-cc56-42d9-b054-300b6073fed1.png)

### Steps to reproduce

use helmfile 0.147.0 under bash/cygwin and run helmfile sync

### Working Helmfile Version

0.147.0

**Comment by yxxhero** [comment]
@itscaro fixed: https://github.com/helmfile/helmfile/pull/451  could you test it on your windows?

**Comment by itscaro** [comment]
@yxxhero Thanks, I will try

**Comment by itscaro** [comment]
@yxxhero Tested on pwsh + busybox and bash + cygwin. all are good ! thanks :-)
