### ISSUE TITLE
Command 'helmfile deps' returns 'There are no repositories defined in your helmfile.yaml.' while it is.

### ISSUE THREAD

**Issue by leotomas837** [helmfile/helmfile#474]
### Operating system

macOS Monterey 12.3.1

### Helmfile Version

0.147.0, darwin arm64

### Helm Version

3.10.1

### Bug description

[1] Command `helmfile deps` results in an error message (with [2.1] and [2.2]), stating that the `repositories` block is not defined in the `helmfile.yaml` file while it is. Note that the return code is yet always 0. 

[2.1] Having the `releases[].dependencies` block into the `helmfile.yaml`, I was also expecting a lock file to be generated, i.e. a `helmfile.lock` as for the `releases[].chart`. But nothing is generated.

[2.2 ] Moving the `releases[].dependencies` block from `helmfile.yaml` to the usual `releases` block in `Chart.yaml`, `helmfile deps` works fine and generates the helm `Chart.lock` file and `charts/` folder. Yet I still get the error message from [1].

[3] [WORK-AROUND] Note that, in the `helmfile.yaml`, including the dependency as a `releases[].chart` (`chart A`) also works (generates the `helmfile.lock`). Then another `releases[].chart` (`chart B`) can be used with the keyword `needs` referencing `chart A` to use it as a dependency (with a fixed version into the `helmfile.lock`). But it looks more like a work-around. 
Is the `releases[].dependencies` block into `helmfile.yaml` a broken feature, or do I use it inproperly ? I have been told that this is because `releases[].dependencies` are managed by an external library, namely `chartify` (as opposed to `releases[].chart`), so this block is not integrated into the helmfile's dependency management system. But should not it be transparent to the users ?

### Example helmfile.yaml

For examples of all the cases, see section `Steps to reproduce`

[1] + [2.1]:

```
repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: mychart
    chart: .
    namespace: mychart
    values:
      - ./values.yaml
    installed: true
    dependencies:
      - version: v1.10.0
        chart: jetstack/cert-manager
```

### Error message you've seen (if any)
```
$> helmfile deps --enable-live-output --debug
Live output is enabled
processing file "helmfile.yaml" in directory "."
changing working directory to "/path/to/home/mychart"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{default map[] map[]}, overrode=<nil>
first-pass uses: &{default map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: repositories:
 1:   - name: jetstack
 2:     url: https://charts.jetstack.io
 3:
 4: releases:
 5:   - name: mychart
 6:     chart: .
 7:     namespace: mychart
 8:     values:
 9:       - ./values.yaml
10:     installed: true
11:     dependencies:
12:       - version: v1.10.0
13:         chart: jetstack/cert-manager
14:

first-pass produced: &{default map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: repositories:
 1:   - name: jetstack
 2:     url: https://charts.jetstack.io
 3:
 4: releases:
 5:   - name: mychart
 6:     chart: .
 7:     namespace: mychart
 8:     values:
 9:       - ./values.yaml
10:     installed: true
11:     dependencies:
12:       - version: v1.10.0
13:         chart: jetstack/cert-manager
14:

merged environment: &{default map[] map[]}
helm:xuSyz> v3.10.1+g9f88ccb
Adding repo jetstack https://charts.jetstack.io
exec: helm repo add jetstack https://charts.jetstack.io --force-update
"jetstack" has been added to your repositories
Chartify process for .
Successfully generated the value file at values.yaml. produced:

running helm repo list
Removing the dependencies field from the original Chart.yaml.
running helm dependency up /var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/chartify4103983402/mychart/mychart
Removing the dependencies field from the original Chart.yaml.
options: {false [/var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/helmfile462959889/mychart-mychart-values-5bdbc4876c] [] [] mychart  true false  [] true}
running helm template --debug=false --output-dir=/var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/chartify4103983402/mychart/mychart/helmx.1.rendered --include-crds mychart /var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/chartify4103983402/mychart/mychart -f /var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/chartify4103983402/mychart/mychart/values.yaml -f /var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/helmfile462959889/mychart-mychart-values-5bdbc4876c --namespace mychart
Removing the dependencies field from the original Chart.yaml.
Removed /var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/helmfile462959889/mychart-mychart-values-5bdbc4876c
Updating dependency /var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/chartify4103983402/mychart/mychart
exec: helm dependency update /var/folders/3r/_xtmgjd569d_lzyb3cvtmt_r0000gn/T/chartify4103983402/mychart/mychart
There are no repositories defined in your helmfile.yaml.
This means helmfile cannot update your dependencies or create a lock file.
See https://github.com/roboll/helmfile/issues/878 for more information.

$> echo $?
0
```

### Steps to reproduce

[1] + [2.1] Command `helmfile deps` does not generate any `helmfile.lock` (block `releases[].dependencies` in `helmfile.yaml` is a broken feature?), and gives the error message ([1]) about the `repositories` as output:
https://github.com/leotomas837/helmfile-bug

[1] + [2.2] Command `helmfile deps` does generates a `Chart.lock` and `charts/` (block `dependencies` in `Chart.yaml`), but still gives the error message ([1]) about the `repositories` as output. Obviously, removing the `repositories` in `helmfile.yaml` does not change anything i.e. I still get the error message from [1] (you can test it yourself if needed):
https://github.com/leotomas837/helmfile-bug2

[3] Example of work-around to include a dependency as a `releases[].chart`. Command `helmfile deps` includes the dependency chart into the `helmfile.lock` and does not give any error message (both problems fixed):
https://github.com/leotomas837/helmfile-workaround

### Working Helmfile Version

The earliest version available for Darwin arm64 is 0.143.0 (repo roboll/helmfile), which does not work too.

### Relevant discussion

https://github.com/roboll/helmfile/issues/2074

**Comment by yxxhero** [comment]
@leotomas837 
```bash
[2.2] Note that moving the 'dependencies' block from helmfile.yaml to Chart.yaml (adapted to the helm syntax), 'helmfile deps' works fine and generates the Chart.lock file and charts/ folder. Is the 'dependencies' block into helmfile.yaml a broken feature, or do I use it not properly ?
```
could you give me a example?

**Comment by leotomas837** [comment]
@yxxhero 

I edited my initial post to give additional details.

I gave all the example in the section ###steps to reproduce :

[1] + [2.1] Broken feature `releases[].dependencies` (or enhancement if it has never been supported ?):
https://github.com/leotomas837/helmfile-bug

[1] + [2.2] Generates `Chart.lock` and `charts/` but still gives the error message [1]:
https://github.com/leotomas837/helmfile-bug2

[3] Work-around:
https://github.com/leotomas837/helmfile-workaround

**Comment by yxxhero** [comment]
@leotomas837 Thanks for your feedback.

**Comment by leotomas837** [comment]
By the way, the error message [1] `There are no repositories defined in your helmfile.yaml` also appears when run `helmfile deps` on a `helmfile.yaml` which reference other `helmfile.yaml` files via `helm files[].path`. Even though everything works fine: the `helmfile.lock` file is generated for each sub-`helmfile.yaml` and the helm repos are added.

**Comment by xiaomudk** [comment]
@yxxhero @leotomas837 Let me try to fix it.

**Comment by yxxhero** [comment]
@xiaomudk ok. assign to you. Thanks very much.

**Comment by xiaomudk** [comment]
First of all, it needs to be clear that `helmfile deps` only records `releases chart name`, not `dependencies` field.
`helmfile deps` is applicable when the chart version is not declared in releases, but you want to lock the chart version.
@mumoshu Am i right?

**Comment by leotomas837** [comment]
@xiaomudk I can bring some context if that is ok.

First issue [1], the following error message is outputted by `helmfile deps` in several cases when it should not. See example in my original post as well as my third comment.

`There are no repositories defined in your helmfile.yaml`

The other 'issue' is that the `releases[].dependencies` are not included in the `helmfile.lock`. I have been told by @mumoshu on the Sweetops Slack chat that this is because the `releases[].dependencies` are managed by an external library, namely chartify (as opposed to `releases[].chart`), and he agreed on the relevance on the enhancement. Should it not not be transparent to the user ?
To answer you about the use of `helmfile deps`, `helmfile deps` is used to lock the `releases[].version` of each release. Let's take the workaround repository ([3]). If the `releases[].version` for the cert-manager chart was `"^v1.9.0"`, it would lock the version `v1.10.0` as this is the last `1.x.x` release of cert-manager. The `helmfile.lock` lock this chart version to make sure that we have a fix version for production for example, so `helmfile sync --skip-deps` uses `v1.10.0` and does not use `v1.11.0` or `v10.10.1` when it is released by cert-manager. But currently it does not lock the version of the dependencies (`releases[].dependencies[].version`). A last point is that, the usual behaviour of lock files is also to lock the ENTIRE dependency tree (versioning of the dependencies of my chart dependencies etc). So a third 'issue' is even that the entire tree is not locked, only the direct charts, not even the dependencies, and not the dependencies of the dependencies etc.

**Comment by leotomas837** [comment]
@xiaomudk Thanks again for volunteering. Do you have any news about it ?

**Comment by yxxhero** [comment]
@xiaomudk any update?

**Comment by xiaomudk** [comment]
@leotomas837 @yxxhero  I'm so sorry to keep you waiting so long, I've been waiting for @mumoshu reply.
In order to make this problem go smoothly, I summarize the following:

### case 1

without any dependencies

```
helmfile.yaml

releases:
  - name: mychart
    chart: .
    namespace: mychart
    values:
      - ./values.yaml
    installed: true
```

```
Chart.yaml

apiVersion: v2
name: mychart
version: 1.0.0
```

**Now:**
show `There are no repositories defined in your helmfile.yaml` message, and return code  0

**Want:**
consistent with Now


### case 2

block `dependencies` in `Chart.yaml`

helmfile has no `dependencies`

```
helmfile.yaml

releases:
  - name: mychart
    chart: .
    namespace: mychart
    values:
      - ./values.yaml
    installed: true
```

```
Chart.yaml

apiVersion: v2
name: mychart
version: 1.0.0


dependencies:
  - name: cert-manager
    version: v1.10.0
    repository: https://charts.jetstack.io
```

**Now:**

* Generates `Chart.lock` and `charts/`

  ```yaml
  Chart.lock

  dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.10.0
  digest: sha256:5fcb5a5a9e25346a9395e3ffba5c38ca6522077efd600cd74745b3683f3050ea
  generated: "2022-12-03T22:19:20.696879+08:00"
  ```
* show `There are no repositories defined in your helmfile.yaml` message, and return code  0

**Want:**
More controversial, I think the current behavior is also okay

The behavior of the helmfile lock file is to lock only the direct charts, not the entire dependency tree.We can discuss in depth whether we need to lock the entire dependency tree in the future.



### case 3

`Chart.yaml` has no `dependencies`

helmfile has `dependencies`

```
helmfile.yaml

releases:
  - name: mychart
    chart: .
    namespace: mychart
    values:
      - ./values.yaml
    installed: true
    dependencies:
      - version: v1.10.0
        chart: jetstack/cert-manager
```

```
Chart.yaml

apiVersion: v2
name: mychart
version: 1.0.0
```

**Now:**

* Not generates `Chart.lock` and `charts/`
* show `There are no repositories defined in your helmfile.yaml` message, and return code  0

**Want:**

* Generate `helmfile.yaml.lock` and record `cert-manager` information
* not show `There are no repositories defined in your helmfile.yaml`

@yxxhero @mumoshu @leotomas837  What do you think?  Thinks.
