### ISSUE TITLE
Error: non-absolute URLs should be in form of repo_name/path_to_chart

### ISSUE THREAD

**Issue by strainovic** [helmfile/helmfile#478]
### Operating system

Windows 10

### Helmfile Version

0.147.0

### Helm Version

3.10.1

### Bug description

After upgrade to the helmfile 0.147.0, I'm unable to sync environment.

### Example helmfile.yaml

not relevant

### Error message you've seen (if any)

Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: third-party%5Cactivemq-artemis

### Steps to reproduce

helmfile -p [namespace] sync

### Working Helmfile Version

0.146.0

**Comment by yxxhero** [comment]
@strainovic Thanks for your issue. fixed: https://github.com/helmfile/helmfile/pull/451
