### ISSUE TITLE
brew zsh autocompletion broken

### ISSUE THREAD

**Issue by aeimer** [helmfile/helmfile#479]
### Operating system

MacOS 12.6

### Helmfile Version

0.147.0

### Helm Version

3.10.0

### Bug description

After the latest call of `brew update ; brew upgrade` the helmfile command fails for autocompletion. brew uninstall and brew install of helmfile did not help.

### Example helmfile.yaml

---

### Error message you've seen (if any)

```
helmfile unknown flag: --generate-bash-completion
                 helmfile --version
```

### Steps to reproduce

---

### Working Helmfile Version

---

**Comment by yxxhero** [comment]
try:
```bash
helmfile completion --help
```

**Comment by aeimer** [comment]
Hi @yxxhero
I have found that help page. But beforehand the autocomplete install with brew worked 100% fine, why is it broken now?

**Comment by yxxhero** [comment]
@aeimer maybe since `helmfile` changed to use `cobra` as the CLI library. I will post an issue for the brew to resolve this.

**Comment by yxxhero** [comment]
@aeimer please show your helmfile version.

**Comment by yxxhero** [comment]
@aeimer BTW. brew is not maintained by us.

**Comment by yxxhero** [comment]
@aeimer if you have other questions. Please post a new issue. thanks very much.

**Comment by aeimer** [comment]
> @aeimer please show your helmfile version.

Well I did: `0.147.0`

@yxxhero have you opened a ticket? Would you mind refrencing it? Thanks for the help

**Comment by yxxhero** [comment]
@aeimer I haven't done it yet. If you have time, you can propose an issue. If need my help. Please tell me.

**Comment by aeimer** [comment]
Here we go: https://github.com/Homebrew/homebrew-core/issues/114158
