### ISSUE TITLE
skipDeps field is not respected

### ISSUE THREAD

**Issue by chrisduong** [helmfile/helmfile#50]
### Operating system

macOS

### Helmfile Version

v0.144.0

### Helm Version

v3.8.1

### Bug description

I set `skipDeps: true` but Helmfile continues to update the dependencies.

```yaml
helmDefaults:
  skipDeps: true
```

### Steps to reproduce

set `skipDeps: true`

**Comment by itscaro** [comment]
Hello, thank you for submitting bug report. Is it possible for you to attach a test case?
