### ISSUE TITLE
"destroy" command doesn't pass value of "--args" parameter into "helm list" command

### ISSUE THREAD

**Issue by mabrarov** [helmfile/helmfile#500]
### Operating system

CentOS 7

### Helmfile Version

0.147.0

### Helm Version

v3.10.0

### Bug description

Refer to https://github.com/mabrarov/helmfile-test/blob/main/README.md#uninstall-helm-release-with-helmfile 

When calling:

```bash
openshift_user='developer' && \
openshift_password='developer' && \
openshift_api_server='https://127.0.0.1:8443' && \
oc login -u "${openshift_user}" -p "${openshift_password}" --insecure-skip-tls-verify "${openshift_api_server}" && \
openshift_token="$(oc whoami -t)" && \
rm -f ~/.kube/config && \
helm_args="--kube-apiserver $(printf '%q' "${openshift_api_server}")" && \
helm_args="${helm_args} --kube-token $(printf '%q' "${openshift_token}")" && \
helm_args="${helm_args} --kube-insecure-skip-tls-verify" && \
helmfile destroy -e local --args "${helm_args}" --debug
```

I get the following output with error:

```text
processing file "helmfile.yaml" in directory "."
changing working directory to "/mnt/hgfs/work/helmfile-test"
first-pass rendering starting for "helmfile.yaml.part.0": inherited=&{local map[] map[]}, overrode=<nil>
first-pass uses: &{local map[] map[]}
first-pass rendering output of "helmfile.yaml.part.0":
 0: environments:
 1:   local: { }
 2: releases:
 3:   - name: "my-release"
 4:     namespace: "myproject"
 5:     createNamespace: false
 6:     chart: "charts/my-chart"
 7:

first-pass produced: &{local map[] map[]}
first-pass rendering result of "helmfile.yaml.part.0": {local map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of "helmfile.yaml.part.0":
 0: environments:
 1:   local: { }
 2: releases:
 3:   - name: "my-release"
 4:     namespace: "myproject"
 5:     createNamespace: false
 6:     chart: "charts/my-chart"
 7:

merged environment: &{local map[] map[]}
helm:nxONG> v3.10.0+gce66412
Building dependency release=my-release, chart=charts/my-chart
exec: helm dependency build charts/my-chart
1 release(s) found in helmfile.yaml

Listing releases matching ^my-release$
exec: helm list --filter ^my-release$ --namespace myproject --uninstalling --deployed --failed --pending
helm:LzZDh> Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused
err: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: list (4 bytes)
  2: --filter (8 bytes)
  3: ^my-release$ (12 bytes)
  4: --namespace (11 bytes)
  5: myproject (9 bytes)
  6: --uninstalling (14 bytes)
  7: --deployed (10 bytes)
  8: --failed (8 bytes)
  9: --pending (9 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused

COMBINED OUTPUT:
  Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused
changing working directory back to "/mnt/hgfs/work/helmfile-test"
in ./helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: list (4 bytes)
  2: --filter (8 bytes)
  3: ^my-release$ (12 bytes)
  4: --namespace (11 bytes)
  5: myproject (9 bytes)
  6: --uninstalling (14 bytes)
  7: --deployed (10 bytes)
  8: --failed (8 bytes)
  9: --pending (9 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused

COMBINED OUTPUT:
  Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused
```

while expected exit status is `0` with removal of `my-release` Helm release from `myproject` namespace of OpenShift cluster which API server address is `https://127.0.0.1:8443` and authentication token is `${openshift_token}`.

Note that `helmfile sync` command works fine - refer to https://github.com/mabrarov/helmfile-test/blob/main/README.md#install-helm-release-with-helmfile

```bash
openshift_user='developer' && \
openshift_password='developer' && \
openshift_api_server='https://127.0.0.1:8443' && \
oc login -u "${openshift_user}" -p "${openshift_password}" --insecure-skip-tls-verify "${openshift_api_server}" && \
openshift_token="$(oc whoami -t)" && \
rm -f ~/.kube/config && \
helm_args="--kube-apiserver $(printf '%q' "${openshift_api_server}")" && \
helm_args="${helm_args} --kube-token $(printf '%q' "${openshift_token}")" && \
helm_args="${helm_args} --kube-insecure-skip-tls-verify" && \
helmfile sync -e local --args "${helm_args}" --wait
```

produces:

```text
Building dependency release=my-release, chart=charts/my-chart
Upgrading release=my-release, chart=charts/my-chart
Release "my-release" does not exist. Installing it now.
NAME: my-release
LAST DEPLOYED: Sun Nov  6 21:26:26 2022
NAMESPACE: myproject
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  http://chart-example.local/

Listing releases matching ^my-release$
my-release      myproject       1               2022-11-06 21:26:26.355166949 +0300 MSK deployed        my-chart-0.1.0  1.23.2


UPDATED RELEASES:
NAME         CHART             VERSION
my-release   charts/my-chart     0.1.0
```

Uninstalling using Helm works fine too - refer to https://github.com/mabrarov/helmfile-test/blob/main/README.md#uninstall-helm-release-with-helm

```bash
openshift_user='developer' && \
openshift_password='developer' && \
openshift_api_server='https://127.0.0.1:8443' && \
oc login -u "${openshift_user}" -p "${openshift_password}" --insecure-skip-tls-verify "${openshift_api_server}" && \
openshift_token="$(oc whoami -t)" && \
rm -f ~/.kube/config && \
openshift_namespace='myproject' && \
helm uninstall my-release \
  --kube-apiserver "${openshift_api_server}" \
  --kube-token "${openshift_token}" \
  --kube-insecure-skip-tls-verify \
  -n "${openshift_namespace}" \
  --wait
```

produces:

```text
release "my-release" uninstalled
```

### Example helmfile.yaml

```yaml
environments:
  local: { }
releases:
  - name: "my-release"
    namespace: "myproject"
    createNamespace: false
    chart: "charts/my-chart"
```

### Error message you've seen (if any)

```text
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused
```

### Steps to reproduce

Refer to "Bug description" section

### Working Helmfile Version

n/a

**Comment by yxxhero** [comment]
@mabrarov please show the full debug output by add --debug flag.

**Comment by mabrarov** [comment]
Hi @yxxhero,

I have updated description of this issue with output you asked for and with repro repo.

Thank you.

**Comment by yxxhero** [comment]
Let me try to explain:

  - It has been provided as-is, and never intended to work reliably because it's fundamentally flawed because we have no way to specify which args to be passed to which `helm` commands being called by which `helmfile` command.
  - However, I periodically see a new user finds it's not working and reporting it as a bug([the most recent example](https://github.com/roboll/helmfile/issues/2034#issuecomment-1147059088)). It's not a fault of the user, but out fault that left this broken feature.
  - Every use-case previsouly covered (by any chance) with `--args` should be covered in new `helmfile.yaml` fields or flags.

And helmfile destroy contains 2 steps:
* helm list
* helm delete

Currently, the value of args only passes to the `helm delete` default.

**Comment by mabrarov** [comment]
Hi @yxxhero,

I agree that `--args` is not the best solution, but Helmfile doesn't support natively `--kube-apiserver`, `--kube-token` and `--kube-insecure-skip-tls-verify` Helm parameters, which makes it hard to use Helmfile without kubeconfig file (Helmfile doesn't support native `--kubeconfig` Helm parameter too).

I implemented a workaround for this issue by creating a temporary kubeconfig file and logging into K8s API server using that file and token:

```bash
kubeconfig_file="$(mktemp --suffix ".yaml")"
chmod 'u=rw,g=,o=' "${kubeconfig_file}"
oc login \
  "${openshift_api_server}" \
  --token "${openshift_token}" \
  --kubeconfig "${kubeconfig_file}" \
  --insecure-skip-tls-verify \
  >/dev/null
```

then I invoke Helmfile using this new kubeconfig file:

```bash
KUBECONFIG="${kubeconfig_file}" helmfile sync/destroy ...
```

The drawback of this solution is the need to remove temporary kubeconfig file.

Thank you.

**Comment by yxxhero** [comment]
@mumoshu ping WDYT?

**Comment by mumoshu** [comment]
> Helmfile doesn't support natively --kube-apiserver, --kube-token and --kube-insecure-skip-tls-verify Helm parameters, which makes it hard to use Helmfile without kubeconfig file (Helmfile doesn't support native --kubeconfig Helm parameter too).

Then we should enhance our helmfile.yaml to support those fields, so that you can do it declaratively!

**Comment by mabrarov** [comment]
Hi @mumoshu,

I like declarative approach, but we cannot put authentication token into helmfile.yaml, i.e. there will be still some options which Helmfile needs to pick from environment or command line.

Thank you.

**Comment by yxxhero** [comment]
@mabrarov do you have an interesting to post a PR?

**Comment by mabrarov** [comment]
Hi @yxxhero,

Sorry, but I do not know Go and Helmfile at the level where I can post a PR.

**Comment by yxxhero** [comment]
@mabrarov Thanks very much. I will try to do that.

**Comment by mabrarov** [comment]
Hi @yxxhero and @mumoshu,

If there will be changes in syntax / options of helmfile.yaml, then maybe it's reasonable to allow overriding options defined in `helmDefaults` section by the same name options under each environment defined in `environments` section (i.e. the same name options need to be implemented for environments defined in `environments` section in that case). IMHO, users of Helmfile should be able to configure these options per environment (if concept of Helmfile environment is not going to be deprecated).

There may be a need in revisiting helmfile.yaml options in order to provide a clean and documented way of overriding options at every layer, e.g. defaults, environment and release. I personally like Ansible and its concept of variables which can be defined at different layers of Ansible inventory (groups which can be nested forming a tree of groups, hosts) and even passed from command line (Ansible extra vars).

Thank you for your work and support!
