### ISSUE TITLE
Allow helmfile statefile to passed by stdin

### ISSUE THREAD

**Issue by ggillies** [helmfile/helmfile#505]
We are looking at using an external tool (jsonnet) to generate a helmfile state file (helmfile.yaml) to pass to helmfile for execution. However, at the moment we have to do something like

```
jsonnet main.jsonnet -o helmfile-from-jsonnet.yaml
helmfile -f helmfile-from-jsonnet.yaml apply
```

It would be really nice if we could have helmfile instead support natively passing it the state file on stdin, so we could instead do

```
jsonnet main.jsonnet | helmfile -f - apply
```

Save us some complexity of creating and cleaning up files on disk.

_Originally posted by @ggillies in https://github.com/helmfile/helmfile/discussions/503_

**Comment by Cinderhaze** [comment]
There are two solutions that come to mind… one trick I usually use is [process substitution](https://unix.stackexchange.com/a/64011) , where you can make a temporary file handle for the process output.  



`jsonnet main.jsonnet <( helmfile -f - apply )`

 You can also use a [named pipe](http://en.wikipedia.org/wiki/Named_pipe)

**Comment by xiaomudk** [comment]
I'm working on it。
