### ISSUE TITLE
Unable to specify kubeContext via environment variable

### ISSUE THREAD

**Issue by sjdrc** [helmfile/helmfile#553]
### Operating system

Ubuntu 22.04 LTS

### Helmfile Version

0.147.0-1

### Helm Version

3.10.2

### Bug description

I want to be able to specify the kubeContext by environment variable. I use helmfile in CI and want to reduce the amount of hardcoded values.

We use GitLab for kubernetes integration and CI is able to access kube contexts by specifying `project_group/project_name:agent_name`.

`project_group/project_name` can be accessed by `${CI_PROJECT_PATH}` and I have some other variables set for the agent name.

### Example helmfile.yaml

```
helmDefaults:
  kubeContext: {{ requiredEnv "CI_PROJECT_PATH" }}:{{ requiredEnv "CLUSTER_NAME" }}
```

### Error message you've seen (if any)

Does not use the correct kubeconfig

### Steps to reproduce

See above

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
```
helmDefaults:
  kubeConfig: {{ requiredEnv "CI_PROJECT_PATH" }}:{{ requiredEnv "CLUSTER_NAME" }}
```

maybe kubeContext?

**Comment by sjdrc** [comment]
Sorry, that was a typo, I meant kubeContext

**Comment by yxxhero** [comment]
@sjdrc please show the debug log by adding --debug flag.

**Comment by sjdrc** [comment]
Never mind it literally works, I have no idea why it wasn't working before.Thanks for your quick replies!
