### ISSUE TITLE
`presync` is not triggered for uninstallation but `postsync` is

### ISSUE THREAD

**Issue by felipecrs** [helmfile/helmfile#584]
### Operating system

N/A

### Helmfile Version

N/A

### Helm Version

N/A

### Bug description

This behavior is [documented](https://helmfile.readthedocs.io/en/latest/#hooks), however, it seems a little weird for me.

Why would `postsync` be triggered for uninstallations but `presync` not? Perhaps we should align this to either start triggering `presync` for uninstallation or stop triggering `postsync` for uninstallation.

But if there is some reason which is unknown to me to keep the current behavior, I would be glad to hear it. If so, perhaps the documentation should mention it too.

### Example helmfile.yaml

If this is required let me know.

### Error message you've seen (if any)

N/A

### Steps to reproduce

If this is required let me know.

### Working Helmfile Version

N/A

**Comment by felipecrs** [comment]
Ok, I just made some tests here and it seems that `postsync` is NOT triggered for uninstallations (helmfile destroy). So maybe only the docs only needs to be adjusted to reflect the reality.

**Comment by yxxhero** [comment]
PR is welcome. Thanks very much.
