### ISSUE TITLE
Drop Helm v2 support

### ISSUE THREAD

**Issue by xiaomudk** [helmfile/helmfile#589]
### Discussed in https://github.com/helmfile/helmfile/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **yxxhero** September 26, 2022</sup>
drop helm v2 support in helmfile v1.0</div>

**Comment by xiaomudk** [comment]
ping

**Comment by xiaomudk** [comment]
Tillerless all code will be removed together, do you have different opinions？ @mumoshu @yxxhero

**Comment by yxxhero** [comment]
@xiaomudk I think so.
