### ISSUE TITLE
inconsistent passing of --post-renderer to helm

### ISSUE THREAD

**Issue by jouve** [helmfile/helmfile#665]
### Operating system

os x

### Helmfile Version

v0.149.0

### Helm Version

v3.10.3

### Bug description

# helmfile template

`helmfile template` does not use the `--post-renderer` options

very simple to reproduce: `helmfile template --post-renderer /bin/false` should fail, it does not because `--post-renderer` is not passed

# helmfile diff

`helmfile diff` does not have a flag `--post-renderer`

### Example helmfile.yaml

--

### Error message you've seen (if any)

--

### Steps to reproduce

--

### Working Helmfile Version

n/a

**Comment by yxxhero** [comment]
@jouve Do you have the interest to post a PR for this? Thanks very much.

**Comment by mumoshu** [comment]
Looking into the pull request that introduced this feature (https://github.com/helmfile/helmfile/pull/510), I realized that we set the post-renderer flag for the helm execution only on sync and apply, but not for template, according to the changes made to `pkg/app/app.go`.
We might need to further modify the app.go to also set the post renderer flag in the helmfile-template command implementation!

**Comment by yxxhero** [comment]
@tanguofu Do you have free time to work on this? Thanks very much.

**Comment by xiaomudk** [comment]
Let me try.
