### ISSUE TITLE
Should exit with non-zero code when command does not exist

### ISSUE THREAD

**Issue by felipecrs** [helmfile/helmfile#673]
### Operating system

N/A

### Helmfile Version

0.150.0

### Helm Version

N/A

### Bug description

```console
$ helmfile whatever
<help message>
$ echo $?
0
```

### Example helmfile.yaml

N/A

### Error message you've seen (if any)

N/A

### Steps to reproduce

As above

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@felipecrs PR is welcome.

**Comment by felipecrs** [comment]
I'll take a look. Thanks. :D

**Comment by yxxhero** [comment]
@felipecrs  any updates? if you need help. please free to ping me.

**Comment by felipecrs** [comment]
Actually thanks for reminding me. I had tried earlier, now I tried again. I actually can't make this work. According to cobra's documentation, `rootCmd.Execute()` was supposed to return an `err` but in fact it's not returning any error.

Out of curiosity, it's indeed entering here:

https://github.com/spf13/cobra/blob/e839bb342f7914fd1bf62041cebd801292e2ccf8/command.go#L877

**Comment by yxxhero** [comment]
@felipecrs Thanks for your feedback. I will check it.

**Comment by yxxhero** [comment]
@felipecrs fixed.

**Comment by felipecrs** [comment]
That's awesome!
