### ISSUE TITLE
key overrides not working

### ISSUE THREAD

**Issue by andreas-noll** [helmfile/helmfile#694]
### Operating system

macOS Ventura

### Helmfile Version

0.150.0

### Helm Version

3.11.1

### Bug description

I run helmfile diff and it fails with "already set in map"

### Example helmfile.yaml

templates:
  default: &default
    labels:
      sync: everyday
charts:
  - name: test
    <<: *default
    chart: test
    labels:
      sync: thur

### Error message you've seen (if any)

key "" already set in map

### Steps to reproduce

override an existing value in a yaml file

### Working Helmfile Version

0.148.1

### Relevant discussion

https://github.com/helmfile/helmfile/pull/396

**Comment by yxxhero** [comment]
Please set environment  variable by the following command：export HELMFILE_GOCCY_GOYAML=true

**Comment by yxxhero** [comment]
Please set environment  variable by the following command：export HELMFILE_GOCCY_GOYAML=true
