### ISSUE TITLE
Error: unknown flag: --load_restrictor with Kustomize 5.0.0

### ISSUE THREAD

**Issue by hinricht** [helmfile/helmfile#743]
### Operating system

Arch Linux

### Helmfile Version

0.150.0-1

### Helm Version

3.11.0

### Bug description

When using a kustomization, `helmfile template` fails with `Error: unknown flag: --load_restrictor]` 
Downgrading `kustomize` to i.e. `4.5.6` fixed it.

### Example helmfile.yaml

helmfile.yaml:
```
helmDefaults:
  kubeContext: "test"

releases:
  - name: test
    namespace: monitoring
    chart: ./test
```

test/kustomization.yaml:
```
resources:
- test.yaml
```

test/test.yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
```

### Error message you've seen (if any)

```
$ helmfile template          
in ./helmfile.yaml: [exit status 1

COMMAND:
  kustomize -o /tmp/chartify559297089/test/monitoring/test/templates/kustomized.yaml build --load_restrictor=none --enable_alpha_plugins /tmp/chartify559297089/test/monitoring/test

OUTPUT:
  Error: unknown flag: --load_restrictor]
```

### Steps to reproduce

https://github.com/hinricht/helmfile-kustomize5.git

### Working Helmfile Version

0.150.0-1

**Comment by yxxhero** [comment]
todos:
- [ ] support Kustomize 5.

**Comment by yxxhero** [comment]
@hinricht from the code. helmfile supports kustomize 5. I can't reproduce your issue. please provide the logs by adding --debug.

**Comment by yxxhero** [comment]
@hinricht ping

**Comment by yxxhero** [comment]
please show the output of `kustomize version --short`.

**Comment by hinricht** [comment]
```
 $ kustomize version --short
Flag --short has been deprecated, and will be removed in the future.
{5.0.0  2023-02-05T00:03:35Z   }
```

**Comment by yxxhero** [comment]
@hinricht fixed: https://github.com/helmfile/chartify/pull/55
