### ISSUE TITLE
supports embedding shell commands directly into the Helmfile.

### ISSUE THREAD

**Issue by xiaomudk** [helmfile/helmfile#764]
### Discussed in https://github.com/helmfile/helmfile/discussions/687

<div type='discussions-op-text'>

<sup>Originally posted by **lucj** February  9, 2023</sup>
In order to create a secret containing a sops/age key I use presync event in a Helmfile dedicated to the Argo-CD installation like this: https://github.com/lucj/k8sapps/blob/main/argocd/helmfile.yaml#L35-L43

Instead of having to create separate scripts (bin/create_secret.sh and bin/delete_secret.sh) I was wondering if the shell command could be directly embeded in the helmfile, something like:

```
...
hooks:
    - events:
      - presync
      showlogs: true
      command: | 
        # Create a sops / age secret key if none already exists
        if [[ -f ./conf/key.txt ]]; then
         echo "age key already exists in ./conf/key.txt"
       else
         age-keygen > ./conf/key.txt
       fi
       # Create secret to give Argo access to the age key
       kubectl create ns argocd || true
       kubectl -n argocd create secret generic age --from-file=key.txt=./conf/key.txt || true
```

Would that make sense ?</div>

**Comment by zer0def** [comment]
Wouldn't this work with the following example?

```
…
  hooks:
  - events: ["presync"]
    command: "/bin/sh"  # has to be an executable, in this specific context, an interpreter
    args:
    - "-ec"
    - |
      <provided script>
…
```

**Comment by yxxhero** [comment]
> Wouldn't this work with the following example?
> 
> ```
> …
>   hooks:
>   - events: ["presync"]
>     command: "/bin/sh"  # has to be an executable, in this specific context, an interpreter
>     args:
>     - "-ec"
>     - |
>       <provided script>
> …
> ```

it's a solution.
