### ISSUE TITLE
Docker image tag `latest` also set on `canary` image

### ISSUE THREAD

**Issue by rmoreas** [helmfile/helmfile#765]
### Operating system

N/A

### Helmfile Version

N/A

### Helm Version

N/A

### Bug description

Seems that the `latest` image tag is also set on the `canary` image while this should only be set on a semantic version tag.

According to the "docker metadata action" documentation, the `latest` should only be added for:

- [type=ref,event=tag](https://github.com/docker/metadata-action#typeref)
- [type=semver,pattern=...](https://github.com/docker/metadata-action#typesemver)
- [type=match,pattern=...](https://github.com/docker/metadata-action#typematch)

Ref: https://github.com/docker/metadata-action#latest-tag

### Example helmfile.yaml

N/A

### Error message you've seen (if any)

N/A

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

**Comment by rmoreas** [comment]
Is there a new release soon? Otherwise the current latest tag is maybe best removed in the image registry.

**Comment by yxxhero** [comment]
Will do.

**Comment by yxxhero** [comment]
@rmoreas I have no permission. wait for the next release.
