### ISSUE TITLE
Unable to fetch an AWS SSM parameter anymore

### ISSUE THREAD

**Issue by cest-pas-faux** [helmfile/helmfile#803]
Hello,

We have a tools image with those components : 
```
HELM_VERSION=v3.11.2
HELMFILE_VERSION=v0.148.1
VALS_VERSION=0.23.0
```

When we try to upgrade helmfile to version 0.149.0 and higher, the only issue is related to a line supposed to fetch an EFS FS ID.

Current configuration : works well and replace the CLUSTER_NAME (provided by the CI) with the right value
`fileSystemId: secretref+awsssm:///{{ .Values.CLUSTER_NAME }}/EfsID`

After the upgrade, we face this error message : 
```
in helmfile.d/001-core.yaml: failed processing release aws-efs-csi-driver: failed to render values files "values/aws-efs-csi-driver.yaml.gotmpl": expand awsssm:///eksXX-tst-us-east-1/EfsID: version can't be converted to Int
```

I played around and tried below syntaxes without success : 

```
fileSystemId: "secretref+awsssm:///{{ .Values.CLUSTER_NAME }}/EfsID"
fileSystemId: ref+awsssm://{{ .Values.CLUSTER_NAME }}/EfsID?region=us-east-1&mode=singleparam
fileSystemId: `"ref+awsssm://eksXX-tst-us-east-1/EfsID?region=us-east-1&mode=singleparam"`
```

``fileSystemId: "ref+awsssm://{{ .Values.CLUSTER_NAME }}/EfsID?region=us-east-1&mode=singleparam"``
Produces : `in helmfile.d/001-core.yaml: failed processing release aws-efs-csi-driver: failed to render values files "values/aws-efs-csi-driver.yaml": expand awsssm://{{ .Values.CLUSTER_NAME }}/EfsID?region=us-east-1&mode=singleparam: parse "awsssm://{{ .Values.CLUSTER_NAME }}/EfsID?region=us-east-1&mode=singleparam": invalid character "{" in host name`

Thanks in advance !

**Comment by yxxhero** [comment]
@cest-pas-faux provider more logs by adding --debug.

**Comment by yxxhero** [comment]
@cest-pas-faux which helmfile version is fine for your case?

**Comment by cest-pas-faux** [comment]
> which helmfile version is fine for your case?

0.148.1 is fine, but upgrading to 0.149.0 breaks the pipeline

> provider more logs by adding --debug.

Already checked, there is nothing more than the error provided

**Comment by yxxhero** [comment]
@cest-pas-faux did you have `VALS_VERSION` env in your environments?

**Comment by cest-pas-faux** [comment]
It's from the docker build for the tools image used to run the pipeline, so it sould be available as a env variable, but it's not added to the environment file and passed to helmfile.

**Comment by yxxhero** [comment]
@cest-pas-faux please try to rename VALS_VERSION to another name. then give me feedback. Thanks so much.

**Comment by cest-pas-faux** [comment]
Hey, after renaming the variable to `TOOLS_VALS_VERSION`, the issue is solved, how did you find this ?
Thanks a lot !
