### ISSUE TITLE
Helmfile Container image is broken for arm64

### ISSUE THREAD

**Issue by lavifb** [helmfile/helmfile#816]
### Operating system

alpine

### Helmfile Version

latest

### Helm Version

latest

### Bug description

Running the `ghcr.io/helmfile/helmfile:v0.152.0` container image on an linux/arm64 arch fails with the following error:
```
/usr/local/bin/helmfile: cannot execute binary file: Exec format error
```

I am pretty sure this is coming from https://github.com/helmfile/helmfile/blob/main/Dockerfile#L92
```
COPY --from=builder /workspace/helmfile/dist/helmfile_linux_amd64 /usr/local/bin/helmfile
```
the amd64 binary is always copied even in the arm64 build.

### Example helmfile.yaml

any helmfile

### Error message you've seen (if any)

`/usr/local/bin/helmfile: cannot execute binary file: Exec format error`

### Steps to reproduce

run ghcr.io/helmfile/helmfile:v0.152.0 on an arm64 machine

### Working Helmfile Version

None

**Comment by lavifb** [comment]
note that an arm64 image is provided. It just doesnt work https://github.com/helmfile/helmfile/pkgs/container/helmfile/81468751?tag=v0.152.0

**Comment by xiaomudk** [comment]
Thanks for the question, are you interested in fixing it?

**Comment by lavifb** [comment]
I could take a swing at it. It should be an easy fix

**Comment by lavifb** [comment]
ugh im going to have to reopen and fix this again. I only fixed the helmfile binary but it turns out all the other ones (helm, sops, etc) are still amd64
