### ISSUE TITLE
helmfile template created manifests containing duplicates when ran multiple times 

### ISSUE THREAD

**Issue by mgazza** [helmfile/helmfile#818]
### Operating system

Linux 7adb7dab9613 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 x86_64 Linux

### Helmfile Version

 0.152.0

### Helm Version

version.BuildInfo{Version:"v3.11.2", GitCommit:"", GitTreeState:"", GoVersion:"go1.20.3"}

### Bug description

helmfile creates duplicate entries each time its ran.

### Example helmfile.yaml

repositories:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.10.0
    set:
      - name: installCRDs
        value: true
releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.10.0
    set:
      - name: installCRDs
        value: true

### Error message you've seen (if any)

The contents of cert-manager/templates/startupapicheck-job.yaml contains a duplicate job.

### Steps to reproduce

`helmfile template --kube-context none --include-crds --skip-tests --output-dir . --output-dir-template "{{ .OutputDir }}"` multiple times

### Working Helmfile Version

Helm version v3.11.1

### Relevant discussion

https://github.com/helm/helm/issues/12010

**Comment by yxxhero** [comment]
@mgazza this is a issue of helm. right? Thanks very much.
