### ISSUE TITLE
Docker image tag latest also set on canary image

### ISSUE THREAD

**Issue by rmoreas** [helmfile/helmfile#822]
### Operating system

N/A

### Helmfile Version

N/A

### Helm Version

N/A

### Bug description

@yxxhero: Seems that #765 didn't fix it. 

### Example helmfile.yaml

N/A

### Error message you've seen (if any)

N/A

### Steps to reproduce

N/A

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@rmoreas did you have time to work     on that.

**Comment by rmoreas** [comment]
I found the error. I used "||" instead of "&&" in the condition for the latest tag. I'll create a PR...

**Comment by yxxhero** [comment]
@rmoreas thanks so much. issue fixed.
