### ISSUE TITLE
Container images for arm64 contain amd64 os binaries

### ISSUE THREAD

**Issue by lavifb** [helmfile/helmfile#825]
### Operating system

arm64 conatiner images

### Helmfile Version

latest

### Helm Version

latest

### Bug description

I went too overboard in #817 and ran the final image with `--platform=$BUILDPLATFORM`. This means that the arm64 build is not emulated and pulls in amd64 base image (as well as any package installed images). This means that the binaries pulled in manually work completely fine (helmfile, helm, etc) but you cannot extend the image because even `apt update` fails.

Relates to original #816 

### Example helmfile.yaml

all

### Error message you've seen (if any)

```
.buildkit_qemu_emulator: /bin/sh: Invalid ELF image for this architecture
```

### Steps to reproduce

run apt update in an arm64 image

### Working Helmfile Version

NA

**Comment by yxxhero** [comment]
@lavifb PR is welcome.

**Comment by lavifb** [comment]
Yup it's up. Thanks for bearing with me here
