### ISSUE TITLE
`helmfile apply` does not use helmDefaults in `diff` stage

### ISSUE THREAD

**Issue by mkgrei** [helmfile/helmfile#856]
### Operating system

Ubuntu 20.04

### Helmfile Version

```
$ helmfile version

▓▓▓ helmfile

  Version              0.152.0
  Git Commit           5650661
  Build Date           30 Mar 23 10:39 JST (1 month ago)
  Commit Date          29 Mar 23 22:27 JST (1 month ago)
  Dirty Build          no
  Go version           1.20.2
  Compiler             gc
  Platform             linux/amd64

  │ A new release is available: 0.152.0 → v0.153.1
  │ https://github.com/helmfile/helmfile/releases/tag/v0.153.1
```

### Helm Version

```
$ helm version
version.BuildInfo{Version:"v3.11.0", GitCommit:"472c5736ab01133de504a826bd9ee12cbe4e7904", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

### Bug description

I am modifying resource with `kubectl-sudo` equivalent options.

Thus, I have the following options in my helmfile.

```
helmDefaults:
  args:
    - '--kube-as-user users:{{ requiredEnv "USER" }}'
    - '--kube-as-group system:masters'
```

These options are used when `diff` or `sync` but operation fails when `apply`.

These options are parsed with `argparser.GetArgs`. For `apply` it is in this line.

https://github.com/helmfile/helmfile/blob/main/pkg/app/app.go#L1428

However, for `apply`, helmfile will `diff` first, and that is in this line.

https://github.com/helmfile/helmfile/blob/main/pkg/app/app.go#L1365

Therefore when using `apply`, helmfile will `diff` without helmDefaults arguments and for environments such as `kubectl-sudo` the command will fail with insufficient permission.

### Example helmfile.yaml

```
helmDefaults:
  args:
    - '--kube-as-user users:{{ requiredEnv "USER" }}'
    - '--kube-as-group system:masters'
```

### Error message you've seen (if any)

```
ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: RELEASENAME
  5: CHARTNAME
  6: --namespace (11 bytes)
  7: NAMESPACE
  8: --values (8 bytes)
  9: VALUES
  10: --values (8 bytes)
  11: VALUES
  12: --detailed-exitcode (19 bytes)
  13: --color (7 bytes)
  14: --reset-values (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to get release RELEASENAME in namespace NAMESPACE: exit status 1: Error: query: failed to query with labels: secrets is forbidden: User "USER" cannot list resource "secrets" in API group "" in the namespace "NAMESPACE"
  Error: plugin "diff" exited with error
```

### Steps to reproduce

Any operation with `helmfile apply` when `kubectl-sudo` equivalent options are needed.

### Working Helmfile Version

none

**Comment by yxxhero** [comment]
@mkgrei thanks for your issue. I'll work on this.

**Comment by yxxhero** [comment]
@mkgrei fixed in 856-helmfile-apply-does-not-use-helmdefaults-in-diff-stage branch. could you help to test it and give me some feedback? thanks so much.
