### ISSUE TITLE
Leakage of possible secrets, if helmfile errored

### ISSUE THREAD

**Issue by jkroepke** [helmfile/helmfile#886]
### Operating system

Ubuntu 22.04

### Helmfile Version

0.153.1

### Helm Version

3.12.0

### Bug description

We are passing secret by using the set function in helmfile.yaml, for example:

If helmfile diff failed, then helmfile exits with an output like this

````
PATH:
  /opt/hostedtoolcache/helm/3.12.0/x64/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
....
````

Since we define secrets as --set through helmfile, they are part of helm diff command and would leak all the secrets on the CI output.

### Example helmfile.yaml

releases:
  - name: helm
    chart: ./charts/helm
    set:
      - name: "password"
        value: "password"

### Error message you've seen (if any)

N/A

### Steps to reproduce

Setup a helmfile using set like in the example. Run helmfile diff in a ways that produce any error. See all the --set arguments on the output.

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@jkroepke valuable idea. Thanks.

**Comment by yxxhero** [comment]
@jkroepke you can try to use the values file now.
