### ISSUE TITLE
helmfile hangs on large diff with --enable-live-output

### ISSUE THREAD

**Issue by jkroepke** [helmfile/helmfile#893]
### Operating system

Ubuntu/MacOS

### Helmfile Version

helmfile version v0.154.0

### Helm Version

version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}

### Bug description

We have an dedicate Helm Chart for maintain the CRDs in our cluster.
At the moment, Kubernetes only allows 1 MB of secret data in total, which limit a helm release to 1 MB.

Our helm chart bundles kube-prometheus-stack CRDs and cert-manager CRDs together. The CRDs together hitting more then 1 MB. As result, we "minified" the CRD YAMLs to single line JSON files.

Everything works fine until helmdiff itself hangs. Running helm diff separately works fine.

The error in helmfile could be buffer related. We have single lines that contains 316KB data. The error does not accours, if ` --enable-live-output` is omit.

### Example helmfile.yaml

helmDefaults:
  createNamespace: true
  timeout: 300
  cleanupOnFail: true
  wait: true

releases:
- name: opsstack-crd
  namespace: default
  chart: ./charts/opsstack-crds

### Error message you've seen (if any)

None. helmfile hangs.

### Steps to reproduce

1. install the CRD chart [opsstack-crds-2.3.0.tgz](https://github.com/helmfile/helmfile/files/11726119/opsstack-crds-2.3.0.tgz) 2. Reconfigure helmfile to use this version: [opsstack-crds-2.4.0.tgz](https://github.com/helmfile/helmfile/files/11726120/opsstack-crds-2.4.0.tgz) 3. Run helmfile diff -f helmfile.yaml --color --enable-live-output --detailed-exitcode --context 3

### Working Helmfile Version

N/A

**Comment by yxxhero** [comment]
@jkroepke PR is welcome.

**Comment by yxxhero** [comment]
@jkroepke one question: is `helm diff` process alive?

**Comment by jkroepke** [comment]
> @jkroepke one question: is `helm diff` process alive?

No. At least the process tree does not show helm diff. helm diff works fine on standalone and helmfile works fine without enable live output.

**Comment by yxxhero** [comment]
@jkroepke thanks for your feedback.

**Comment by yxxhero** [comment]
@jkroepke welcome to post PRs for this issue. thanks so much.

**Comment by yxxhero** [comment]
ok. I will work on this.

**Comment by flabatut** [comment]
hi there, up for grab ?
