### ISSUE TITLE
Diffs in labels on Deployment template not correctly shown

### ISSUE THREAD

**Issue by GeiserX** [helmfile/helmfile#967]
### Operating system

MacOS Ventura 13.5

### Helmfile Version

v0.155.1

### Helm Version

v3.12.2

### Bug description

While upgrading my nginx controller, I've noticed something odd, which is shown here:

![Screenshot](https://github.com/helmfile/helmfile/assets/9169332/d52c6ba7-90f8-42b3-9afd-826754ea5550)

I checked and it has the same internal letter representation.

### Example helmfile.yaml

```helmfile.yaml
context: test

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: ingress-external
    namespace: ingress
    chart: ingress-nginx/ingress-nginx
    version: 4.7.1# 4.1.2 before
    labels:
      app: ingress-external
      release: ingress-external
    values:
      - ingress-external.yaml
...
   ```
   
 ```ingress-external.yaml
 # Any will do, but include, for example:
commonLabels:
  service-level: white
  service-time: 9x5
 ```

### Error message you've seen (if any)

none

### Steps to reproduce

Private repo

### Working Helmfile Version

v0.155.1

**Comment by yxxhero** [comment]
@GeiserX are there any helmfile versions that work as expected?

**Comment by yxxhero** [comment]
@GeiserX I think that it's an issue of helm-diff. please post a new in helm-diff project.
