### ISSUE TITLE
Possible race condition signal: killed

### ISSUE THREAD

**Issue by skizot722** [helmfile/helmfile#981]
### Operating system

Ubuntu 18.04 LTS

### Helmfile Version

ghcr.io/helmfile/helmfile-debian-stable-slim:v0.154.0

### Helm Version

3.12

### Bug description

Similar to https://github.com/roboll/helmfile/issues/1687 we're encountering a problem with executions being killed. We have 121 releases (some with deps on others), being executed in a docker container, on a 16-core / 64 GB RAM VM, with --concurrency 16. It seems to happen almost always 3 minutes into execution. Eventually we are able to get a successful run, after enough retries. The behavior feels like a race condition, as the author of the other issue alluded to. Please let me know if you need any more info. Thanks!

### Example helmfile.yaml

Let me know if you need details, but I cannot provide the entire helmfile as it contains many local charts.

### Error message you've seen (if any)

```
  | [2023-08-17T14:47:28Z] ERROR:
  | [2023-08-17T14:47:28Z]   signal: killed
  | [2023-08-17T14:47:28Z]
  | [2023-08-17T14:47:28Z] EXIT STATUS
  | [2023-08-17T14:47:28Z]   -1
```

### Steps to reproduce

Please let me know which specific details

### Working Helmfile Version

Unknown

**Comment by yxxhero** [comment]
@skizot722 could you post the output of `dmesg -T` when killed?
