### ISSUE TITLE
Secrets not found errors when deploying multiple release to one kubernetes environment in parallel 

### ISSUE THREAD

**Issue by WOW-Lin** [helmfile/helmfile#992]
### Operating system

Ubuntu 22.04

### Helmfile Version

v0.142.0

### Helm Version

v3.3.1

### Bug description

We are using helmfile for installing helm chart and the version of helmfile we are using is v0.142.0.
I tried to put --debug after:
./helmfile -e ${{ parameters.environment }} apply
But it doesn't accept this flag.
For your question, I observed it happening when we add a new feature to our application (which create a new version of the helm chart, is it considered as 'first time'?)

### Example helmfile.yaml

https://github.com/roboll/helmfile/releases/download/v0.142.0/helmfile_linux_amd64

### Error message you've seen (if any)

When deploying multiple applications to the same environment in parallel, we encounter this error:
in one build agent

STDERR:
  Error: UPGRADE FAILED: update: failed to update: secrets "sh.helm.release.v1.my-release-1.v7" not found
in another build agent

STDERR:
 Error: UPGRADE FAILED: update: failed to update: secrets "sh.helm.release.v1.my-release-2.v7" not found
But it is successful when we are deploying it one by one, e.g my-release-1 and then my-release-2

### Steps to reproduce

Running two release in parallel on Azure DevOps 

### Working Helmfile Version

Not sure

**Comment by WOW-Lin** [comment]
Hi @yxxhero ,
Just wondering if you had a chance to look at this issue?

**Comment by yxxhero** [comment]
@WOW-Lin  this week.

**Comment by WOW-Lin** [comment]
> @WOW-Lin this week.

Thanks @yxxhero , will be very appreciated on your solution in advance.

**Comment by WOW-Lin** [comment]
Do you have any updates @yxxhero ?

**Comment by yxxhero** [comment]
@WOW-Lin NO. I am debugging.

**Comment by yxxhero** [comment]
@WOW-Lin could you try to use the latest version to run the same case? and give me the latest logs.

**Comment by yxxhero** [comment]
@WOW-Lin ping

**Comment by WOW-Lin** [comment]
> @WOW-Lin ping

Thanks @yxxhero , I will give you the result today.

**Comment by WOW-Lin** [comment]
Hi @yxxhero ,
We are using the latest helmfile (0.157.0), still the same error. See screenshot below, two pipelines running at the same time.
<img width="1007" alt="Screen Shot 2023-10-12 at 3 05 52 pm" src="https://github.com/helmfile/helmfile/assets/32916018/d0a0e9c9-2d7e-49fd-afcf-50d4a2daa310">

<img width="1062" alt="Screen Shot 2023-10-12 at 3 06 03 pm" src="https://github.com/helmfile/helmfile/assets/32916018/9fb32d4a-476e-4542-a7a0-755334816afc">

**Comment by yxxhero** [comment]
@WOW-Lin thanks. please show the log by adding --debug.

**Comment by WOW-Lin** [comment]
Hi @yxxhero ,
I put a --debug in like this:
./helmfile --debug -e ${{ parameters.environment }} apply

It seems showing the same level of errors for both:
<img width="1090" alt="Screen Shot 2023-10-12 at 4 23 13 pm" src="https://github.com/helmfile/helmfile/assets/32916018/75052e36-4b7d-4879-be6a-d105a48d1071">

**Comment by yxxhero** [comment]
@WOW-Lin  could you give the all logs? thanks so much.

**Comment by WOW-Lin** [comment]
@yxxhero , here it is:
[log text.zip](https://github.com/helmfile/helmfile/files/12877728/log.text.zip)

**Comment by yxxhero** [comment]
@WOW-Lin I can't reproduce this issue. could you post a demo project?

**Comment by WOW-Lin** [comment]
@yxxhero ,
Just wondering if you ran two pipelines in the same time and deploy to the same cluster when you tried to reproduce the issue?

**Comment by yxxhero** [comment]
@WOW-Lin two pipeline and same time same release?

**Comment by WOW-Lin** [comment]
> @WOW-Lin two pipeline and same time same release?

@yxxhero ,
Our folder structure is like below:

**Project_Root/
- Release_A/pipeline.yaml
- Release_B/pipeline.yaml**
So Release_A and Release_B are two different pipelines.

And our deployment deploys to environment in order: **dev -> uat -> pt**.

When we commit code to Project_Root repo, Release_A and Release_B pipelines are triggered at the same time and get deployed to dev -> uat -> pt.

**Comment by yxxhero** [comment]
are there some same between releaseA and releaseB?  @WOW-Lin

**Comment by WOW-Lin** [comment]
> are there some same between releaseA and releaseB? @WOW-Lin

@yxxhero , the deployment steps are the same between releaseA and releaseB (please note: releaseA and releaseB are two applications)

**Comment by WOW-Lin** [comment]
Do you have any update @yxxhero ?

**Comment by WOW-Lin** [comment]
Hi @yxxhero ,
Not sure why it is marking as stale, we are still blocking by this.

**Comment by yxxhero** [comment]
@WOW-Lin sorry. marked by the bot.

**Comment by yxxhero** [comment]
@WOW-Lin I am trying to find a way to debug this issue.
